/* Generated By:JJTree: Do not edit this line. ASTArrayLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jacop.fz;

public
class ASTArrayLiteral extends SimpleNode {
  public ASTArrayLiteral(int id) {
    super(id);
  }

  public ASTArrayLiteral(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=202e530287da94b180c6398800ba6763 (do not edit this line) */
