/* Generated By:JJTree: Do not edit this line. ASTBoolTiExprTail.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jacop.fz;

public
class ASTBoolTiExprTail extends SimpleNode {
  public ASTBoolTiExprTail(int id) {
    super(id);
  }

  public ASTBoolTiExprTail(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=496227cffee43f02b3a8900a545f68ec (do not edit this line) */
