/* Generated By:JJTree: Do not edit this line. ASTConstraintItems.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jacop.fz;

public
class ASTConstraintItems extends SimpleNode {
  public ASTConstraintItems(int id) {
    super(id);
  }

  public ASTConstraintItems(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=60b3e4b609289f91e44a11c308747d0e (do not edit this line) */
