/* Generated By:JJTree: Do not edit this line. ASTmodel.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jacop.fz;

public
class ASTmodel extends SimpleNode {
  public ASTmodel(int id) {
    super(id);
  }

  public ASTmodel(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d95e4dcdd3575461a442953496f39870 (do not edit this line) */
