/* Generated By:JJTree: Do not edit this line. ASTModelEnd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jacop.fz;

public
class ASTModelEnd extends SimpleNode {
  public ASTModelEnd(int id) {
    super(id);
  }

  public ASTModelEnd(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0af8f7b6768b9f7c201f373925cb2eea (do not edit this line) */
