/* Generated By:JJTree: Do not edit this line. ASTSolveItem.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jacop.fz;

public
class ASTSolveItem extends SimpleNode {
  public ASTSolveItem(int id) {
    super(id);
  }

  public ASTSolveItem(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d209a8d7b91afbf47ff8aedd7170ddac (do not edit this line) */
