/* Generated By:JJTree: Do not edit this line. ASTVarDeclItems.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jacop.fz;

public
class ASTVarDeclItems extends SimpleNode {
  public ASTVarDeclItems(int id) {
    super(id);
  }

  public ASTVarDeclItems(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9ef6a84b2642322f0cbfd3b3bc638942 (do not edit this line) */
