/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package org.jacop.fz;

public interface ParserTreeConstants
{
  public int JJTMODEL = 0;
  public int JJTVOID = 1;
  public int JJTVARDECLITEMS = 2;
  public int JJTCONSTRAINTITEMS = 3;
  public int JJTMODELEND = 4;
  public int JJTVARDECLITEM = 5;
  public int JJTCONSTRAINT = 6;
  public int JJTCONSTELEM = 7;
  public int JJTSOLVEITEM = 8;
  public int JJTSOLVEKIND = 9;
  public int JJTBOOLTIEXPRTAIL = 10;
  public int JJTINTTIEXPRTAIL = 11;
  public int JJTFLOATTIEXPRTAIL = 12;
  public int JJTSETTIEXPRTAIL = 13;
  public int JJTANNEXPR = 14;
  public int JJTSCALARFLATEXPR = 15;
  public int JJTINTFLATEXPR = 16;
  public int JJTVARIABLEEXPR = 17;
  public int JJTSOLVEEXPR = 18;
  public int JJTINTLITERALS = 19;
  public int JJTSETLITERAL = 20;
  public int JJTARRAYLITERAL = 21;
  public int JJTANNOTATION = 22;


  public String[] jjtNodeName = {
    "model",
    "void",
    "VarDeclItems",
    "ConstraintItems",
    "ModelEnd",
    "VarDeclItem",
    "Constraint",
    "ConstElem",
    "SolveItem",
    "SolveKind",
    "BoolTiExprTail",
    "IntTiExprTail",
    "FloatTiExprTail",
    "SetTiExprTail",
    "AnnExpr",
    "ScalarFlatExpr",
    "IntFlatExpr",
    "VariableExpr",
    "SolveExpr",
    "IntLiterals",
    "SetLiteral",
    "ArrayLiteral",
    "Annotation",
  };
}
/* JavaCC - OriginalChecksum=f4637e5cf3ae566765588305ad354942 (do not edit this line) */
