/*
 * generated by Xtext
 */
package ch.hilbri.assist.schedulingdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SchedulingDSLUiModule extends ch.hilbri.assist.schedulingdsl.ui.AbstractSchedulingDSLUiModule {
	public SchedulingDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
