sudo: required

language: java

jdk: oraclejdk8

env: DISPLAY=:99.0

install: true

before_install:
 - sudo apt-get update
 - sudo apt-get install gnome-themes-standard
 - sudo apt-get install metacity
 - sudo apt-get install libwebkit-dev

before_script:
 - sh -e /etc/init.d/xvfb start
 - sleep 10         # give xvfb some time to start
 - metacity --sm-disable --replace &
 - sleep 10         # give metacity some time to start
 
script:
 - export
 - cd ch.hilbri.assist.releng
 - mvn clean verify -U
 - sh -e /etc/init.d/xvfb stop

notifications:
  email:
    recipients:
       - robert.hilbrich@dlr.de
    on_success: always 
    on_failure: always 
    
deploy:
  provider: releases
  api_key:
    secure: UasB0wvz/o6Z+a3k0n3t6P1UhvnlgC3889WCuyKFbjs26U89ejXbHigJ62uEt8KkW1GQyWkpFvu+AYP35Ctl2gP5bpkpAmrZD5OGmiPJd8JPVSj+ZhXdD/+eUGoxMsNTXFJzhP8lMnjXtsTk2O2IqaZ+30twoTYzJve97qJVjTY=
  file_glob: true
  file: ../ch.hilbri.assist.releng.product.gui/target/products/ASSIST-*
  skip_cleanup: true
  on:
    repo: RobertHilbrich/assist-public
    tags: true
