/*
 * generated by Xtext
 */
package ch.hilbri.assist.mappingdsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import ch.hilbri.assist.mappingdsl.ui.internal.MappingDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MappingDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MappingDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MappingDSLActivator.getInstance().getInjector(MappingDSLActivator.CH_HILBRI_ASSIST_MAPPINGDSL_MAPPINGDSL);
	}
	
}
