/**
 */
package ch.hilbri.assist.datamodel.model.provider;

import ch.hilbri.assist.datamodel.model.util.ModelAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ModelItemProviderAdapterFactory extends ModelAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ModelItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.AssistModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AssistModelItemProvider assistModelItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.AssistModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAssistModelAdapter() {
		if (assistModelItemProvider == null) {
			assistModelItemProvider = new AssistModelItemProvider(this);
		}

		return assistModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.GlobalBlock} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GlobalBlockItemProvider globalBlockItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.GlobalBlock}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGlobalBlockAdapter() {
		if (globalBlockItemProvider == null) {
			globalBlockItemProvider = new GlobalBlockItemProvider(this);
		}

		return globalBlockItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.CompatibleIoTypesBlock} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompatibleIoTypesBlockItemProvider compatibleIoTypesBlockItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.CompatibleIoTypesBlock}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompatibleIoTypesBlockAdapter() {
		if (compatibleIoTypesBlockItemProvider == null) {
			compatibleIoTypesBlockItemProvider = new CompatibleIoTypesBlockItemProvider(this);
		}

		return compatibleIoTypesBlockItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.CompatibleIoTypeEntry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompatibleIoTypeEntryItemProvider compatibleIoTypeEntryItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.CompatibleIoTypeEntry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompatibleIoTypeEntryAdapter() {
		if (compatibleIoTypeEntryItemProvider == null) {
			compatibleIoTypeEntryItemProvider = new CompatibleIoTypeEntryItemProvider(this);
		}

		return compatibleIoTypeEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.CableWeightDataBlock} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CableWeightDataBlockItemProvider cableWeightDataBlockItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.CableWeightDataBlock}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCableWeightDataBlockAdapter() {
		if (cableWeightDataBlockItemProvider == null) {
			cableWeightDataBlockItemProvider = new CableWeightDataBlockItemProvider(this);
		}

		return cableWeightDataBlockItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.CableWeightEntry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CableWeightEntryItemProvider cableWeightEntryItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.CableWeightEntry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCableWeightEntryAdapter() {
		if (cableWeightEntryItemProvider == null) {
			cableWeightEntryItemProvider = new CableWeightEntryItemProvider(this);
		}

		return cableWeightEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.ProtectionLevelDataBlock} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProtectionLevelDataBlockItemProvider protectionLevelDataBlockItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.ProtectionLevelDataBlock}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProtectionLevelDataBlockAdapter() {
		if (protectionLevelDataBlockItemProvider == null) {
			protectionLevelDataBlockItemProvider = new ProtectionLevelDataBlockItemProvider(this);
		}

		return protectionLevelDataBlockItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.ProtectionLevelEntry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProtectionLevelEntryItemProvider protectionLevelEntryItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.ProtectionLevelEntry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProtectionLevelEntryAdapter() {
		if (protectionLevelEntryItemProvider == null) {
			protectionLevelEntryItemProvider = new ProtectionLevelEntryItemProvider(this);
		}

		return protectionLevelEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.CompartmentsBlock} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompartmentsBlockItemProvider compartmentsBlockItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.CompartmentsBlock}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompartmentsBlockAdapter() {
		if (compartmentsBlockItemProvider == null) {
			compartmentsBlockItemProvider = new CompartmentsBlockItemProvider(this);
		}

		return compartmentsBlockItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.HardwareElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HardwareElementItemProvider hardwareElementItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.HardwareElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHardwareElementAdapter() {
		if (hardwareElementItemProvider == null) {
			hardwareElementItemProvider = new HardwareElementItemProvider(this);
		}

		return hardwareElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.MetricParametersBlock} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MetricParametersBlockItemProvider metricParametersBlockItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.MetricParametersBlock}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMetricParametersBlockAdapter() {
		if (metricParametersBlockItemProvider == null) {
			metricParametersBlockItemProvider = new MetricParametersBlockItemProvider(this);
		}

		return metricParametersBlockItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.MetricParameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MetricParameterItemProvider metricParameterItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.MetricParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMetricParameterAdapter() {
		if (metricParameterItemProvider == null) {
			metricParameterItemProvider = new MetricParameterItemProvider(this);
		}

		return metricParameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.Compartment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompartmentItemProvider compartmentItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.Compartment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompartmentAdapter() {
		if (compartmentItemProvider == null) {
			compartmentItemProvider = new CompartmentItemProvider(this);
		}

		return compartmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.RDC} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RDCItemProvider rdcItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.RDC}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRDCAdapter() {
		if (rdcItemProvider == null) {
			rdcItemProvider = new RDCItemProvider(this);
		}

		return rdcItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.Connector} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConnectorItemProvider connectorItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.Connector}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConnectorAdapter() {
		if (connectorItemProvider == null) {
			connectorItemProvider = new ConnectorItemProvider(this);
		}

		return connectorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.Pin} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PinItemProvider pinItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.Pin}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPinAdapter() {
		if (pinItemProvider == null) {
			pinItemProvider = new PinItemProvider(this);
		}

		return pinItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.InternallyConnectedPinEntry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InternallyConnectedPinEntryItemProvider internallyConnectedPinEntryItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.InternallyConnectedPinEntry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInternallyConnectedPinEntryAdapter() {
		if (internallyConnectedPinEntryItemProvider == null) {
			internallyConnectedPinEntryItemProvider = new InternallyConnectedPinEntryItemProvider(this);
		}

		return internallyConnectedPinEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.InterfacesBlock} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InterfacesBlockItemProvider interfacesBlockItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.InterfacesBlock}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInterfacesBlockAdapter() {
		if (interfacesBlockItemProvider == null) {
			interfacesBlockItemProvider = new InterfacesBlockItemProvider(this);
		}

		return interfacesBlockItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.EqInterfaceOrGroup} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EqInterfaceOrGroupItemProvider eqInterfaceOrGroupItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.EqInterfaceOrGroup}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEqInterfaceOrGroupAdapter() {
		if (eqInterfaceOrGroupItemProvider == null) {
			eqInterfaceOrGroupItemProvider = new EqInterfaceOrGroupItemProvider(this);
		}

		return eqInterfaceOrGroupItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.EqInterface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EqInterfaceItemProvider eqInterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.EqInterface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEqInterfaceAdapter() {
		if (eqInterfaceItemProvider == null) {
			eqInterfaceItemProvider = new EqInterfaceItemProvider(this);
		}

		return eqInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.InterfaceGroupsBlock} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InterfaceGroupsBlockItemProvider interfaceGroupsBlockItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.InterfaceGroupsBlock}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInterfaceGroupsBlockAdapter() {
		if (interfaceGroupsBlockItemProvider == null) {
			interfaceGroupsBlockItemProvider = new InterfaceGroupsBlockItemProvider(this);
		}

		return interfaceGroupsBlockItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.EqInterfaceGroup} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EqInterfaceGroupItemProvider eqInterfaceGroupItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.EqInterfaceGroup}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEqInterfaceGroupAdapter() {
		if (eqInterfaceGroupItemProvider == null) {
			eqInterfaceGroupItemProvider = new EqInterfaceGroupItemProvider(this);
		}

		return eqInterfaceGroupItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.ImplicitEqInterfaceMemberDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImplicitEqInterfaceMemberDefinitionItemProvider implicitEqInterfaceMemberDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.ImplicitEqInterfaceMemberDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImplicitEqInterfaceMemberDefinitionAdapter() {
		if (implicitEqInterfaceMemberDefinitionItemProvider == null) {
			implicitEqInterfaceMemberDefinitionItemProvider = new ImplicitEqInterfaceMemberDefinitionItemProvider(this);
		}

		return implicitEqInterfaceMemberDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.ImplicitEqInterfaceMemberDefinitionAttributesAndValues} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImplicitEqInterfaceMemberDefinitionAttributesAndValuesItemProvider implicitEqInterfaceMemberDefinitionAttributesAndValuesItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.ImplicitEqInterfaceMemberDefinitionAttributesAndValues}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImplicitEqInterfaceMemberDefinitionAttributesAndValuesAdapter() {
		if (implicitEqInterfaceMemberDefinitionAttributesAndValuesItemProvider == null) {
			implicitEqInterfaceMemberDefinitionAttributesAndValuesItemProvider = new ImplicitEqInterfaceMemberDefinitionAttributesAndValuesItemProvider(this);
		}

		return implicitEqInterfaceMemberDefinitionAttributesAndValuesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.EqInterfaceGroupWithCombinedDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EqInterfaceGroupWithCombinedDefinitionItemProvider eqInterfaceGroupWithCombinedDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.EqInterfaceGroupWithCombinedDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEqInterfaceGroupWithCombinedDefinitionAdapter() {
		if (eqInterfaceGroupWithCombinedDefinitionItemProvider == null) {
			eqInterfaceGroupWithCombinedDefinitionItemProvider = new EqInterfaceGroupWithCombinedDefinitionItemProvider(this);
		}

		return eqInterfaceGroupWithCombinedDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.RestrictionsBlock} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RestrictionsBlockItemProvider restrictionsBlockItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.RestrictionsBlock}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRestrictionsBlockAdapter() {
		if (restrictionsBlockItemProvider == null) {
			restrictionsBlockItemProvider = new RestrictionsBlockItemProvider(this);
		}

		return restrictionsBlockItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.DislocalityRelation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DislocalityRelationItemProvider dislocalityRelationItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.DislocalityRelation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDislocalityRelationAdapter() {
		if (dislocalityRelationItemProvider == null) {
			dislocalityRelationItemProvider = new DislocalityRelationItemProvider(this);
		}

		return dislocalityRelationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.ColocalityRelation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ColocalityRelationItemProvider colocalityRelationItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.ColocalityRelation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createColocalityRelationAdapter() {
		if (colocalityRelationItemProvider == null) {
			colocalityRelationItemProvider = new ColocalityRelationItemProvider(this);
		}

		return colocalityRelationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.DeploymentSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeploymentSpecificationItemProvider deploymentSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.DeploymentSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeploymentSpecificationAdapter() {
		if (deploymentSpecificationItemProvider == null) {
			deploymentSpecificationItemProvider = new DeploymentSpecificationItemProvider(this);
		}

		return deploymentSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.DeploymentImplicitDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeploymentImplicitDefinitionItemProvider deploymentImplicitDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.DeploymentImplicitDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeploymentImplicitDefinitionAdapter() {
		if (deploymentImplicitDefinitionItemProvider == null) {
			deploymentImplicitDefinitionItemProvider = new DeploymentImplicitDefinitionItemProvider(this);
		}

		return deploymentImplicitDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.DeploymentImplicitDefinitionAttributeAndValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeploymentImplicitDefinitionAttributeAndValueItemProvider deploymentImplicitDefinitionAttributeAndValueItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.DeploymentImplicitDefinitionAttributeAndValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeploymentImplicitDefinitionAttributeAndValueAdapter() {
		if (deploymentImplicitDefinitionAttributeAndValueItemProvider == null) {
			deploymentImplicitDefinitionAttributeAndValueItemProvider = new DeploymentImplicitDefinitionAttributeAndValueItemProvider(this);
		}

		return deploymentImplicitDefinitionAttributeAndValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.ValidDeployment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ValidDeploymentItemProvider validDeploymentItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.ValidDeployment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createValidDeploymentAdapter() {
		if (validDeploymentItemProvider == null) {
			validDeploymentItemProvider = new ValidDeploymentItemProvider(this);
		}

		return validDeploymentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ch.hilbri.assist.datamodel.model.InvalidDeployment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InvalidDeploymentItemProvider invalidDeploymentItemProvider;

	/**
	 * This creates an adapter for a {@link ch.hilbri.assist.datamodel.model.InvalidDeployment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInvalidDeploymentAdapter() {
		if (invalidDeploymentItemProvider == null) {
			invalidDeploymentItemProvider = new InvalidDeploymentItemProvider(this);
		}

		return invalidDeploymentItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (assistModelItemProvider != null) assistModelItemProvider.dispose();
		if (globalBlockItemProvider != null) globalBlockItemProvider.dispose();
		if (compatibleIoTypesBlockItemProvider != null) compatibleIoTypesBlockItemProvider.dispose();
		if (compatibleIoTypeEntryItemProvider != null) compatibleIoTypeEntryItemProvider.dispose();
		if (cableWeightDataBlockItemProvider != null) cableWeightDataBlockItemProvider.dispose();
		if (cableWeightEntryItemProvider != null) cableWeightEntryItemProvider.dispose();
		if (protectionLevelDataBlockItemProvider != null) protectionLevelDataBlockItemProvider.dispose();
		if (protectionLevelEntryItemProvider != null) protectionLevelEntryItemProvider.dispose();
		if (compartmentsBlockItemProvider != null) compartmentsBlockItemProvider.dispose();
		if (hardwareElementItemProvider != null) hardwareElementItemProvider.dispose();
		if (metricParametersBlockItemProvider != null) metricParametersBlockItemProvider.dispose();
		if (metricParameterItemProvider != null) metricParameterItemProvider.dispose();
		if (compartmentItemProvider != null) compartmentItemProvider.dispose();
		if (rdcItemProvider != null) rdcItemProvider.dispose();
		if (connectorItemProvider != null) connectorItemProvider.dispose();
		if (pinItemProvider != null) pinItemProvider.dispose();
		if (internallyConnectedPinEntryItemProvider != null) internallyConnectedPinEntryItemProvider.dispose();
		if (interfacesBlockItemProvider != null) interfacesBlockItemProvider.dispose();
		if (eqInterfaceOrGroupItemProvider != null) eqInterfaceOrGroupItemProvider.dispose();
		if (eqInterfaceItemProvider != null) eqInterfaceItemProvider.dispose();
		if (interfaceGroupsBlockItemProvider != null) interfaceGroupsBlockItemProvider.dispose();
		if (eqInterfaceGroupItemProvider != null) eqInterfaceGroupItemProvider.dispose();
		if (implicitEqInterfaceMemberDefinitionItemProvider != null) implicitEqInterfaceMemberDefinitionItemProvider.dispose();
		if (implicitEqInterfaceMemberDefinitionAttributesAndValuesItemProvider != null) implicitEqInterfaceMemberDefinitionAttributesAndValuesItemProvider.dispose();
		if (eqInterfaceGroupWithCombinedDefinitionItemProvider != null) eqInterfaceGroupWithCombinedDefinitionItemProvider.dispose();
		if (restrictionsBlockItemProvider != null) restrictionsBlockItemProvider.dispose();
		if (dislocalityRelationItemProvider != null) dislocalityRelationItemProvider.dispose();
		if (colocalityRelationItemProvider != null) colocalityRelationItemProvider.dispose();
		if (deploymentSpecificationItemProvider != null) deploymentSpecificationItemProvider.dispose();
		if (deploymentImplicitDefinitionItemProvider != null) deploymentImplicitDefinitionItemProvider.dispose();
		if (deploymentImplicitDefinitionAttributeAndValueItemProvider != null) deploymentImplicitDefinitionAttributeAndValueItemProvider.dispose();
		if (validDeploymentItemProvider != null) validDeploymentItemProvider.dispose();
		if (invalidDeploymentItemProvider != null) invalidDeploymentItemProvider.dispose();
	}

}
