/**
 * generated by Xtext
 */
package ch.hilbri.assist.mappingdsl.ui.contentassist;

import ch.hilbri.assist.mappingdsl.ui.contentassist.AbstractMappingDSLProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class MappingDSLProposalProvider extends AbstractMappingDSLProposalProvider {
}
