/*
* generated by Xtext
*/
package ch.hilbri.assist.mappingdsl.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class MappingDSLGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class AssistModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AssistModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGlobalKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cSystemNameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cSystemNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cSystemNameSTRINGTerminalRuleCall_4_0 = (RuleCall)cSystemNameAssignment_4.eContents().get(0);
		private final Keyword cSemicolonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cCompartmentsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cCompartmentsCompartmentParserRuleCall_7_0 = (RuleCall)cCompartmentsAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cInterfacesKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cEqInterfacesAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cEqInterfacesEqInterfaceParserRuleCall_8_2_0 = (RuleCall)cEqInterfacesAssignment_8_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8_3 = (Keyword)cGroup_8.eContents().get(3);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cInterfaceGroupsKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cEqInterfaceGroupsAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cEqInterfaceGroupsEqInterfaceGroupParserRuleCall_9_2_0 = (RuleCall)cEqInterfaceGroupsAssignment_9_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9_3 = (Keyword)cGroup_9.eContents().get(3);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cRestrictionsKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Assignment cDislocalityRelationsAssignment_10_2 = (Assignment)cGroup_10.eContents().get(2);
		private final RuleCall cDislocalityRelationsDislocalityRelationParserRuleCall_10_2_0 = (RuleCall)cDislocalityRelationsAssignment_10_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10_3 = (Keyword)cGroup_10.eContents().get(3);
		
		//AssistModel:
		//	"Global" "{" "System name" "=" systemName=STRING ";" "}" compartments+=Compartment? ("Interfaces" "{"
		//	eqInterfaces+=EqInterface+ "}")? ("InterfaceGroups" "{" eqInterfaceGroups+=EqInterfaceGroup+ "}")? ("Restrictions"
		//	"{" dislocalityRelations+=DislocalityRelation* "}")?;
		public ParserRule getRule() { return rule; }

		//"Global" "{" "System name" "=" systemName=STRING ";" "}" compartments+=Compartment? ("Interfaces" "{"
		//eqInterfaces+=EqInterface+ "}")? ("InterfaceGroups" "{" eqInterfaceGroups+=EqInterfaceGroup+ "}")? ("Restrictions" "{"
		//dislocalityRelations+=DislocalityRelation* "}")?
		public Group getGroup() { return cGroup; }

		//"Global"
		public Keyword getGlobalKeyword_0() { return cGlobalKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"System name"
		public Keyword getSystemNameKeyword_2() { return cSystemNameKeyword_2; }

		//"="
		public Keyword getEqualsSignKeyword_3() { return cEqualsSignKeyword_3; }

		//systemName=STRING
		public Assignment getSystemNameAssignment_4() { return cSystemNameAssignment_4; }

		//STRING
		public RuleCall getSystemNameSTRINGTerminalRuleCall_4_0() { return cSystemNameSTRINGTerminalRuleCall_4_0; }

		//";"
		public Keyword getSemicolonKeyword_5() { return cSemicolonKeyword_5; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }

		//compartments+=Compartment?
		public Assignment getCompartmentsAssignment_7() { return cCompartmentsAssignment_7; }

		//Compartment
		public RuleCall getCompartmentsCompartmentParserRuleCall_7_0() { return cCompartmentsCompartmentParserRuleCall_7_0; }

		//("Interfaces" "{" eqInterfaces+=EqInterface+ "}")?
		public Group getGroup_8() { return cGroup_8; }

		//"Interfaces"
		public Keyword getInterfacesKeyword_8_0() { return cInterfacesKeyword_8_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_8_1() { return cLeftCurlyBracketKeyword_8_1; }

		//eqInterfaces+=EqInterface+
		public Assignment getEqInterfacesAssignment_8_2() { return cEqInterfacesAssignment_8_2; }

		//EqInterface
		public RuleCall getEqInterfacesEqInterfaceParserRuleCall_8_2_0() { return cEqInterfacesEqInterfaceParserRuleCall_8_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8_3() { return cRightCurlyBracketKeyword_8_3; }

		//("InterfaceGroups" "{" eqInterfaceGroups+=EqInterfaceGroup+ "}")?
		public Group getGroup_9() { return cGroup_9; }

		//"InterfaceGroups"
		public Keyword getInterfaceGroupsKeyword_9_0() { return cInterfaceGroupsKeyword_9_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_9_1() { return cLeftCurlyBracketKeyword_9_1; }

		//eqInterfaceGroups+=EqInterfaceGroup+
		public Assignment getEqInterfaceGroupsAssignment_9_2() { return cEqInterfaceGroupsAssignment_9_2; }

		//EqInterfaceGroup
		public RuleCall getEqInterfaceGroupsEqInterfaceGroupParserRuleCall_9_2_0() { return cEqInterfaceGroupsEqInterfaceGroupParserRuleCall_9_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9_3() { return cRightCurlyBracketKeyword_9_3; }

		//("Restrictions" "{" dislocalityRelations+=DislocalityRelation* "}")?
		public Group getGroup_10() { return cGroup_10; }

		//"Restrictions"
		public Keyword getRestrictionsKeyword_10_0() { return cRestrictionsKeyword_10_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_10_1() { return cLeftCurlyBracketKeyword_10_1; }

		//dislocalityRelations+=DislocalityRelation*
		public Assignment getDislocalityRelationsAssignment_10_2() { return cDislocalityRelationsAssignment_10_2; }

		//DislocalityRelation
		public RuleCall getDislocalityRelationsDislocalityRelationParserRuleCall_10_2_0() { return cDislocalityRelationsDislocalityRelationParserRuleCall_10_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_10_3() { return cRightCurlyBracketKeyword_10_3; }
	}

	public class CompartmentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Compartment");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCompartmentKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final UnorderedGroup cUnorderedGroup_3 = (UnorderedGroup)cGroup.eContents().get(3);
		private final Group cGroup_3_0 = (Group)cUnorderedGroup_3.eContents().get(0);
		private final Keyword cManufacturerKeyword_3_0_0 = (Keyword)cGroup_3_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_3_0_1 = (Keyword)cGroup_3_0.eContents().get(1);
		private final Assignment cManufacturerAssignment_3_0_2 = (Assignment)cGroup_3_0.eContents().get(2);
		private final RuleCall cManufacturerSTRINGTerminalRuleCall_3_0_2_0 = (RuleCall)cManufacturerAssignment_3_0_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3_0_3 = (Keyword)cGroup_3_0.eContents().get(3);
		private final Group cGroup_3_1 = (Group)cUnorderedGroup_3.eContents().get(1);
		private final Keyword cPowerSupplyKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_3_1_1 = (Keyword)cGroup_3_1.eContents().get(1);
		private final Assignment cPowerSupplyAssignment_3_1_2 = (Assignment)cGroup_3_1.eContents().get(2);
		private final RuleCall cPowerSupplySTRINGTerminalRuleCall_3_1_2_0 = (RuleCall)cPowerSupplyAssignment_3_1_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3_1_3 = (Keyword)cGroup_3_1.eContents().get(3);
		private final Group cGroup_3_2 = (Group)cUnorderedGroup_3.eContents().get(2);
		private final Keyword cSideKeyword_3_2_0 = (Keyword)cGroup_3_2.eContents().get(0);
		private final Keyword cEqualsSignKeyword_3_2_1 = (Keyword)cGroup_3_2.eContents().get(1);
		private final Assignment cSideAssignment_3_2_2 = (Assignment)cGroup_3_2.eContents().get(2);
		private final RuleCall cSideSTRINGTerminalRuleCall_3_2_2_0 = (RuleCall)cSideAssignment_3_2_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3_2_3 = (Keyword)cGroup_3_2.eContents().get(3);
		private final Group cGroup_3_3 = (Group)cUnorderedGroup_3.eContents().get(3);
		private final Keyword cZoneKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Keyword cEqualsSignKeyword_3_3_1 = (Keyword)cGroup_3_3.eContents().get(1);
		private final Assignment cZoneAssignment_3_3_2 = (Assignment)cGroup_3_3.eContents().get(2);
		private final RuleCall cZoneSTRINGTerminalRuleCall_3_3_2_0 = (RuleCall)cZoneAssignment_3_3_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3_3_3 = (Keyword)cGroup_3_3.eContents().get(3);
		private final Assignment cRdcsAssignment_3_4 = (Assignment)cUnorderedGroup_3.eContents().get(4);
		private final RuleCall cRdcsRDCParserRuleCall_3_4_0 = (RuleCall)cRdcsAssignment_3_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Compartment:
		//	"Compartment" name=ID "{" (("Manufacturer" "=" manufacturer=STRING ";")? & ("PowerSupply" "=" powerSupply=STRING
		//	";")? & ("Side" "=" side=STRING ";")? & ("Zone" "=" zone=STRING ";")? & rdcs+=RDC*) "}";
		public ParserRule getRule() { return rule; }

		//"Compartment" name=ID "{" (("Manufacturer" "=" manufacturer=STRING ";")? & ("PowerSupply" "=" powerSupply=STRING ";")? &
		//("Side" "=" side=STRING ";")? & ("Zone" "=" zone=STRING ";")? & rdcs+=RDC*) "}"
		public Group getGroup() { return cGroup; }

		//"Compartment"
		public Keyword getCompartmentKeyword_0() { return cCompartmentKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("Manufacturer" "=" manufacturer=STRING ";")? & ("PowerSupply" "=" powerSupply=STRING ";")? & ("Side" "=" side=STRING
		//";")? & ("Zone" "=" zone=STRING ";")? & rdcs+=RDC*
		public UnorderedGroup getUnorderedGroup_3() { return cUnorderedGroup_3; }

		//("Manufacturer" "=" manufacturer=STRING ";")?
		public Group getGroup_3_0() { return cGroup_3_0; }

		//"Manufacturer"
		public Keyword getManufacturerKeyword_3_0_0() { return cManufacturerKeyword_3_0_0; }

		//"="
		public Keyword getEqualsSignKeyword_3_0_1() { return cEqualsSignKeyword_3_0_1; }

		//manufacturer=STRING
		public Assignment getManufacturerAssignment_3_0_2() { return cManufacturerAssignment_3_0_2; }

		//STRING
		public RuleCall getManufacturerSTRINGTerminalRuleCall_3_0_2_0() { return cManufacturerSTRINGTerminalRuleCall_3_0_2_0; }

		//";"
		public Keyword getSemicolonKeyword_3_0_3() { return cSemicolonKeyword_3_0_3; }

		//("PowerSupply" "=" powerSupply=STRING ";")?
		public Group getGroup_3_1() { return cGroup_3_1; }

		//"PowerSupply"
		public Keyword getPowerSupplyKeyword_3_1_0() { return cPowerSupplyKeyword_3_1_0; }

		//"="
		public Keyword getEqualsSignKeyword_3_1_1() { return cEqualsSignKeyword_3_1_1; }

		//powerSupply=STRING
		public Assignment getPowerSupplyAssignment_3_1_2() { return cPowerSupplyAssignment_3_1_2; }

		//STRING
		public RuleCall getPowerSupplySTRINGTerminalRuleCall_3_1_2_0() { return cPowerSupplySTRINGTerminalRuleCall_3_1_2_0; }

		//";"
		public Keyword getSemicolonKeyword_3_1_3() { return cSemicolonKeyword_3_1_3; }

		//("Side" "=" side=STRING ";")?
		public Group getGroup_3_2() { return cGroup_3_2; }

		//"Side"
		public Keyword getSideKeyword_3_2_0() { return cSideKeyword_3_2_0; }

		//"="
		public Keyword getEqualsSignKeyword_3_2_1() { return cEqualsSignKeyword_3_2_1; }

		//side=STRING
		public Assignment getSideAssignment_3_2_2() { return cSideAssignment_3_2_2; }

		//STRING
		public RuleCall getSideSTRINGTerminalRuleCall_3_2_2_0() { return cSideSTRINGTerminalRuleCall_3_2_2_0; }

		//";"
		public Keyword getSemicolonKeyword_3_2_3() { return cSemicolonKeyword_3_2_3; }

		//("Zone" "=" zone=STRING ";")?
		public Group getGroup_3_3() { return cGroup_3_3; }

		//"Zone"
		public Keyword getZoneKeyword_3_3_0() { return cZoneKeyword_3_3_0; }

		//"="
		public Keyword getEqualsSignKeyword_3_3_1() { return cEqualsSignKeyword_3_3_1; }

		//zone=STRING
		public Assignment getZoneAssignment_3_3_2() { return cZoneAssignment_3_3_2; }

		//STRING
		public RuleCall getZoneSTRINGTerminalRuleCall_3_3_2_0() { return cZoneSTRINGTerminalRuleCall_3_3_2_0; }

		//";"
		public Keyword getSemicolonKeyword_3_3_3() { return cSemicolonKeyword_3_3_3; }

		//rdcs+=RDC*
		public Assignment getRdcsAssignment_3_4() { return cRdcsAssignment_3_4; }

		//RDC
		public RuleCall getRdcsRDCParserRuleCall_3_4_0() { return cRdcsRDCParserRuleCall_3_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class RDCElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RDC");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRDCKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cManufacturerKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cEqualsSignKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cManufacturerAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cManufacturerSTRINGTerminalRuleCall_3_2_0 = (RuleCall)cManufacturerAssignment_3_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3_3 = (Keyword)cGroup_3.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cPowerSupplyKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cEqualsSignKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cPowerSupplyAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cPowerSupplySTRINGTerminalRuleCall_4_2_0 = (RuleCall)cPowerSupplyAssignment_4_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_4_3 = (Keyword)cGroup_4.eContents().get(3);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTypeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cEqualsSignKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cRdcTypeAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cRdcTypeSTRINGTerminalRuleCall_5_2_0 = (RuleCall)cRdcTypeAssignment_5_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_5_3 = (Keyword)cGroup_5.eContents().get(3);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cESSKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cEqualsSignKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cEssAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cEssSTRINGTerminalRuleCall_6_2_0 = (RuleCall)cEssAssignment_6_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_6_3 = (Keyword)cGroup_6.eContents().get(3);
		private final Assignment cConnectorsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cConnectorsConnectorParserRuleCall_7_0 = (RuleCall)cConnectorsAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cGenericPropertiesKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cMetricParametersAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cMetricParametersMetricParameterParserRuleCall_8_2_0 = (RuleCall)cMetricParametersAssignment_8_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8_3 = (Keyword)cGroup_8.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//RDC:
		//	"RDC" name=ID "{" ("Manufacturer" "=" manufacturer=STRING ";")? ("PowerSupply" "=" powerSupply=STRING ";")? ("Type"
		//	"=" rdcType=STRING ";")? ("ESS" "=" ess=STRING ";")? connectors+=Connector+ ("Generic properties" "{"
		//	metricParameters+=MetricParameter* "}")? "}";
		public ParserRule getRule() { return rule; }

		//"RDC" name=ID "{" ("Manufacturer" "=" manufacturer=STRING ";")? ("PowerSupply" "=" powerSupply=STRING ";")? ("Type" "="
		//rdcType=STRING ";")? ("ESS" "=" ess=STRING ";")? connectors+=Connector+ ("Generic properties" "{"
		//metricParameters+=MetricParameter* "}")? "}"
		public Group getGroup() { return cGroup; }

		//"RDC"
		public Keyword getRDCKeyword_0() { return cRDCKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("Manufacturer" "=" manufacturer=STRING ";")?
		public Group getGroup_3() { return cGroup_3; }

		//"Manufacturer"
		public Keyword getManufacturerKeyword_3_0() { return cManufacturerKeyword_3_0; }

		//"="
		public Keyword getEqualsSignKeyword_3_1() { return cEqualsSignKeyword_3_1; }

		//manufacturer=STRING
		public Assignment getManufacturerAssignment_3_2() { return cManufacturerAssignment_3_2; }

		//STRING
		public RuleCall getManufacturerSTRINGTerminalRuleCall_3_2_0() { return cManufacturerSTRINGTerminalRuleCall_3_2_0; }

		//";"
		public Keyword getSemicolonKeyword_3_3() { return cSemicolonKeyword_3_3; }

		//("PowerSupply" "=" powerSupply=STRING ";")?
		public Group getGroup_4() { return cGroup_4; }

		//"PowerSupply"
		public Keyword getPowerSupplyKeyword_4_0() { return cPowerSupplyKeyword_4_0; }

		//"="
		public Keyword getEqualsSignKeyword_4_1() { return cEqualsSignKeyword_4_1; }

		//powerSupply=STRING
		public Assignment getPowerSupplyAssignment_4_2() { return cPowerSupplyAssignment_4_2; }

		//STRING
		public RuleCall getPowerSupplySTRINGTerminalRuleCall_4_2_0() { return cPowerSupplySTRINGTerminalRuleCall_4_2_0; }

		//";"
		public Keyword getSemicolonKeyword_4_3() { return cSemicolonKeyword_4_3; }

		//("Type" "=" rdcType=STRING ";")?
		public Group getGroup_5() { return cGroup_5; }

		//"Type"
		public Keyword getTypeKeyword_5_0() { return cTypeKeyword_5_0; }

		//"="
		public Keyword getEqualsSignKeyword_5_1() { return cEqualsSignKeyword_5_1; }

		//rdcType=STRING
		public Assignment getRdcTypeAssignment_5_2() { return cRdcTypeAssignment_5_2; }

		//STRING
		public RuleCall getRdcTypeSTRINGTerminalRuleCall_5_2_0() { return cRdcTypeSTRINGTerminalRuleCall_5_2_0; }

		//";"
		public Keyword getSemicolonKeyword_5_3() { return cSemicolonKeyword_5_3; }

		//("ESS" "=" ess=STRING ";")?
		public Group getGroup_6() { return cGroup_6; }

		//"ESS"
		public Keyword getESSKeyword_6_0() { return cESSKeyword_6_0; }

		//"="
		public Keyword getEqualsSignKeyword_6_1() { return cEqualsSignKeyword_6_1; }

		//ess=STRING
		public Assignment getEssAssignment_6_2() { return cEssAssignment_6_2; }

		//STRING
		public RuleCall getEssSTRINGTerminalRuleCall_6_2_0() { return cEssSTRINGTerminalRuleCall_6_2_0; }

		//";"
		public Keyword getSemicolonKeyword_6_3() { return cSemicolonKeyword_6_3; }

		//connectors+=Connector+
		public Assignment getConnectorsAssignment_7() { return cConnectorsAssignment_7; }

		//Connector
		public RuleCall getConnectorsConnectorParserRuleCall_7_0() { return cConnectorsConnectorParserRuleCall_7_0; }

		//("Generic properties" "{" metricParameters+=MetricParameter* "}")?
		public Group getGroup_8() { return cGroup_8; }

		//"Generic properties"
		public Keyword getGenericPropertiesKeyword_8_0() { return cGenericPropertiesKeyword_8_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_8_1() { return cLeftCurlyBracketKeyword_8_1; }

		//metricParameters+=MetricParameter*
		public Assignment getMetricParametersAssignment_8_2() { return cMetricParametersAssignment_8_2; }

		//MetricParameter
		public RuleCall getMetricParametersMetricParameterParserRuleCall_8_2_0() { return cMetricParametersMetricParameterParserRuleCall_8_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8_3() { return cRightCurlyBracketKeyword_8_3; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}

	public class ConnectorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Connector");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cConnectorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cAvailableEqInterfacesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cAvailableEqInterfacesAvailableEqInterfaceParserRuleCall_3_0 = (RuleCall)cAvailableEqInterfacesAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Connector:
		//	"Connector" name=ID "{" availableEqInterfaces+=AvailableEqInterface* "}";
		public ParserRule getRule() { return rule; }

		//"Connector" name=ID "{" availableEqInterfaces+=AvailableEqInterface* "}"
		public Group getGroup() { return cGroup; }

		//"Connector"
		public Keyword getConnectorKeyword_0() { return cConnectorKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//availableEqInterfaces+=AvailableEqInterface*
		public Assignment getAvailableEqInterfacesAssignment_3() { return cAvailableEqInterfacesAssignment_3; }

		//AvailableEqInterface
		public RuleCall getAvailableEqInterfacesAvailableEqInterfaceParserRuleCall_3_0() { return cAvailableEqInterfacesAvailableEqInterfaceParserRuleCall_3_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class AvailableEqInterfaceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AvailableEqInterface");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cCountAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cCountINTTerminalRuleCall_0_0 = (RuleCall)cCountAssignment_0.eContents().get(0);
		private final Keyword cInterfaceWithTypeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cEqInterfaceTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cEqInterfaceTypeEqInterfaceTypeEnumRuleCall_2_0 = (RuleCall)cEqInterfaceTypeAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//AvailableEqInterface:
		//	count=INT "interface with type" eqInterfaceType=EqInterfaceType ";";
		public ParserRule getRule() { return rule; }

		//count=INT "interface with type" eqInterfaceType=EqInterfaceType ";"
		public Group getGroup() { return cGroup; }

		//count=INT
		public Assignment getCountAssignment_0() { return cCountAssignment_0; }

		//INT
		public RuleCall getCountINTTerminalRuleCall_0_0() { return cCountINTTerminalRuleCall_0_0; }

		//"interface with type"
		public Keyword getInterfaceWithTypeKeyword_1() { return cInterfaceWithTypeKeyword_1; }

		//eqInterfaceType=EqInterfaceType
		public Assignment getEqInterfaceTypeAssignment_2() { return cEqInterfaceTypeAssignment_2; }

		//EqInterfaceType
		public RuleCall getEqInterfaceTypeEqInterfaceTypeEnumRuleCall_2_0() { return cEqInterfaceTypeEqInterfaceTypeEnumRuleCall_2_0; }

		//";"
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}

	public class EqInterfaceGroupElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EqInterfaceGroup");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGroupKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cEqInterfacesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cEqInterfacesEqInterfaceCrossReference_3_0 = (CrossReference)cEqInterfacesAssignment_3.eContents().get(0);
		private final RuleCall cEqInterfacesEqInterfaceIDTerminalRuleCall_3_0_1 = (RuleCall)cEqInterfacesEqInterfaceCrossReference_3_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cEqInterfacesAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cEqInterfacesEqInterfaceCrossReference_4_1_0 = (CrossReference)cEqInterfacesAssignment_4_1.eContents().get(0);
		private final RuleCall cEqInterfacesEqInterfaceIDTerminalRuleCall_4_1_0_1 = (RuleCall)cEqInterfacesEqInterfaceCrossReference_4_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		/// * SOFTWARE * / EqInterfaceGroup:
		//	"Group" name=ID "{" eqInterfaces+=[EqInterface] ("," eqInterfaces+=[EqInterface])+ "}";
		public ParserRule getRule() { return rule; }

		//"Group" name=ID "{" eqInterfaces+=[EqInterface] ("," eqInterfaces+=[EqInterface])+ "}"
		public Group getGroup() { return cGroup; }

		//"Group"
		public Keyword getGroupKeyword_0() { return cGroupKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//eqInterfaces+=[EqInterface]
		public Assignment getEqInterfacesAssignment_3() { return cEqInterfacesAssignment_3; }

		//[EqInterface]
		public CrossReference getEqInterfacesEqInterfaceCrossReference_3_0() { return cEqInterfacesEqInterfaceCrossReference_3_0; }

		//ID
		public RuleCall getEqInterfacesEqInterfaceIDTerminalRuleCall_3_0_1() { return cEqInterfacesEqInterfaceIDTerminalRuleCall_3_0_1; }

		//("," eqInterfaces+=[EqInterface])+
		public Group getGroup_4() { return cGroup_4; }

		//","
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }

		//eqInterfaces+=[EqInterface]
		public Assignment getEqInterfacesAssignment_4_1() { return cEqInterfacesAssignment_4_1; }

		//[EqInterface]
		public CrossReference getEqInterfacesEqInterfaceCrossReference_4_1_0() { return cEqInterfacesEqInterfaceCrossReference_4_1_0; }

		//ID
		public RuleCall getEqInterfacesEqInterfaceIDTerminalRuleCall_4_1_0_1() { return cEqInterfacesEqInterfaceIDTerminalRuleCall_4_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class EqInterfaceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EqInterface");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInterfaceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cInterfaceSystemKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cEqualsSignKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cSystemAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cSystemSTRINGTerminalRuleCall_3_2_0 = (RuleCall)cSystemAssignment_3_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3_3 = (Keyword)cGroup_3.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cSubAtaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cEqualsSignKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cSubAtaAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cSubAtaSTRINGTerminalRuleCall_4_2_0 = (RuleCall)cSubAtaAssignment_4_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_4_3 = (Keyword)cGroup_4.eContents().get(3);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cResourceKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cEqualsSignKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cResourceAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cResourceSTRINGTerminalRuleCall_5_2_0 = (RuleCall)cResourceAssignment_5_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_5_3 = (Keyword)cGroup_5.eContents().get(3);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cLineNameKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cEqualsSignKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cLineNameAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cLineNameSTRINGTerminalRuleCall_6_2_0 = (RuleCall)cLineNameAssignment_6_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_6_3 = (Keyword)cGroup_6.eContents().get(3);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cWiringLaneKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cEqualsSignKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cWiringLaneAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cWiringLaneSTRINGTerminalRuleCall_7_2_0 = (RuleCall)cWiringLaneAssignment_7_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_7_3 = (Keyword)cGroup_7.eContents().get(3);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cGrpInfoKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cEqualsSignKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cGrpInfoAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cGrpInfoSTRINGTerminalRuleCall_8_2_0 = (RuleCall)cGrpInfoAssignment_8_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_8_3 = (Keyword)cGroup_8.eContents().get(3);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cRouteKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cEqualsSignKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cRouteAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cRouteSTRINGTerminalRuleCall_9_2_0 = (RuleCall)cRouteAssignment_9_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_9_3 = (Keyword)cGroup_9.eContents().get(3);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cPwSup1Keyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cEqualsSignKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Assignment cPwSup1Assignment_10_2 = (Assignment)cGroup_10.eContents().get(2);
		private final RuleCall cPwSup1STRINGTerminalRuleCall_10_2_0 = (RuleCall)cPwSup1Assignment_10_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_10_3 = (Keyword)cGroup_10.eContents().get(3);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cEmhZone1Keyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Keyword cEqualsSignKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Assignment cEmhZone1Assignment_11_2 = (Assignment)cGroup_11.eContents().get(2);
		private final RuleCall cEmhZone1STRINGTerminalRuleCall_11_2_0 = (RuleCall)cEmhZone1Assignment_11_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_11_3 = (Keyword)cGroup_11.eContents().get(3);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cTypeKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Keyword cEqualsSignKeyword_12_1 = (Keyword)cGroup_12.eContents().get(1);
		private final Assignment cIoTypeAssignment_12_2 = (Assignment)cGroup_12.eContents().get(2);
		private final RuleCall cIoTypeEqInterfaceTypeEnumRuleCall_12_2_0 = (RuleCall)cIoTypeAssignment_12_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_12_3 = (Keyword)cGroup_12.eContents().get(3);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cGenericPropertiesKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_13_1 = (Keyword)cGroup_13.eContents().get(1);
		private final Assignment cMetricParametersAssignment_13_2 = (Assignment)cGroup_13.eContents().get(2);
		private final RuleCall cMetricParametersMetricParameterParserRuleCall_13_2_0 = (RuleCall)cMetricParametersAssignment_13_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13_3 = (Keyword)cGroup_13.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//EqInterface:
		//	"Interface" name=ID "{" ("InterfaceSystem" "=" system=STRING ";")? ("SubAta" "=" subAta=STRING ";")? ("Resource" "="
		//	resource=STRING ";")? ("LineName" "=" lineName=STRING ";")? ("WiringLane" "=" wiringLane=STRING ";")? ("GrpInfo" "="
		//	grpInfo=STRING ";")? ("Route" "=" route=STRING ";")? ("PwSup1" "=" pwSup1=STRING ";")? ("EmhZone1" "="
		//	emhZone1=STRING ";")? ("Type" "=" ioType=EqInterfaceType ";")? ("Generic properties" "{"
		//	metricParameters+=MetricParameter* "}")? "}";
		public ParserRule getRule() { return rule; }

		//"Interface" name=ID "{" ("InterfaceSystem" "=" system=STRING ";")? ("SubAta" "=" subAta=STRING ";")? ("Resource" "="
		//resource=STRING ";")? ("LineName" "=" lineName=STRING ";")? ("WiringLane" "=" wiringLane=STRING ";")? ("GrpInfo" "="
		//grpInfo=STRING ";")? ("Route" "=" route=STRING ";")? ("PwSup1" "=" pwSup1=STRING ";")? ("EmhZone1" "=" emhZone1=STRING
		//";")? ("Type" "=" ioType=EqInterfaceType ";")? ("Generic properties" "{" metricParameters+=MetricParameter* "}")? "}"
		public Group getGroup() { return cGroup; }

		//"Interface"
		public Keyword getInterfaceKeyword_0() { return cInterfaceKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("InterfaceSystem" "=" system=STRING ";")?
		public Group getGroup_3() { return cGroup_3; }

		//"InterfaceSystem"
		public Keyword getInterfaceSystemKeyword_3_0() { return cInterfaceSystemKeyword_3_0; }

		//"="
		public Keyword getEqualsSignKeyword_3_1() { return cEqualsSignKeyword_3_1; }

		//system=STRING
		public Assignment getSystemAssignment_3_2() { return cSystemAssignment_3_2; }

		//STRING
		public RuleCall getSystemSTRINGTerminalRuleCall_3_2_0() { return cSystemSTRINGTerminalRuleCall_3_2_0; }

		//";"
		public Keyword getSemicolonKeyword_3_3() { return cSemicolonKeyword_3_3; }

		//("SubAta" "=" subAta=STRING ";")?
		public Group getGroup_4() { return cGroup_4; }

		//"SubAta"
		public Keyword getSubAtaKeyword_4_0() { return cSubAtaKeyword_4_0; }

		//"="
		public Keyword getEqualsSignKeyword_4_1() { return cEqualsSignKeyword_4_1; }

		//subAta=STRING
		public Assignment getSubAtaAssignment_4_2() { return cSubAtaAssignment_4_2; }

		//STRING
		public RuleCall getSubAtaSTRINGTerminalRuleCall_4_2_0() { return cSubAtaSTRINGTerminalRuleCall_4_2_0; }

		//";"
		public Keyword getSemicolonKeyword_4_3() { return cSemicolonKeyword_4_3; }

		//("Resource" "=" resource=STRING ";")?
		public Group getGroup_5() { return cGroup_5; }

		//"Resource"
		public Keyword getResourceKeyword_5_0() { return cResourceKeyword_5_0; }

		//"="
		public Keyword getEqualsSignKeyword_5_1() { return cEqualsSignKeyword_5_1; }

		//resource=STRING
		public Assignment getResourceAssignment_5_2() { return cResourceAssignment_5_2; }

		//STRING
		public RuleCall getResourceSTRINGTerminalRuleCall_5_2_0() { return cResourceSTRINGTerminalRuleCall_5_2_0; }

		//";"
		public Keyword getSemicolonKeyword_5_3() { return cSemicolonKeyword_5_3; }

		//("LineName" "=" lineName=STRING ";")?
		public Group getGroup_6() { return cGroup_6; }

		//"LineName"
		public Keyword getLineNameKeyword_6_0() { return cLineNameKeyword_6_0; }

		//"="
		public Keyword getEqualsSignKeyword_6_1() { return cEqualsSignKeyword_6_1; }

		//lineName=STRING
		public Assignment getLineNameAssignment_6_2() { return cLineNameAssignment_6_2; }

		//STRING
		public RuleCall getLineNameSTRINGTerminalRuleCall_6_2_0() { return cLineNameSTRINGTerminalRuleCall_6_2_0; }

		//";"
		public Keyword getSemicolonKeyword_6_3() { return cSemicolonKeyword_6_3; }

		//("WiringLane" "=" wiringLane=STRING ";")?
		public Group getGroup_7() { return cGroup_7; }

		//"WiringLane"
		public Keyword getWiringLaneKeyword_7_0() { return cWiringLaneKeyword_7_0; }

		//"="
		public Keyword getEqualsSignKeyword_7_1() { return cEqualsSignKeyword_7_1; }

		//wiringLane=STRING
		public Assignment getWiringLaneAssignment_7_2() { return cWiringLaneAssignment_7_2; }

		//STRING
		public RuleCall getWiringLaneSTRINGTerminalRuleCall_7_2_0() { return cWiringLaneSTRINGTerminalRuleCall_7_2_0; }

		//";"
		public Keyword getSemicolonKeyword_7_3() { return cSemicolonKeyword_7_3; }

		//("GrpInfo" "=" grpInfo=STRING ";")?
		public Group getGroup_8() { return cGroup_8; }

		//"GrpInfo"
		public Keyword getGrpInfoKeyword_8_0() { return cGrpInfoKeyword_8_0; }

		//"="
		public Keyword getEqualsSignKeyword_8_1() { return cEqualsSignKeyword_8_1; }

		//grpInfo=STRING
		public Assignment getGrpInfoAssignment_8_2() { return cGrpInfoAssignment_8_2; }

		//STRING
		public RuleCall getGrpInfoSTRINGTerminalRuleCall_8_2_0() { return cGrpInfoSTRINGTerminalRuleCall_8_2_0; }

		//";"
		public Keyword getSemicolonKeyword_8_3() { return cSemicolonKeyword_8_3; }

		//("Route" "=" route=STRING ";")?
		public Group getGroup_9() { return cGroup_9; }

		//"Route"
		public Keyword getRouteKeyword_9_0() { return cRouteKeyword_9_0; }

		//"="
		public Keyword getEqualsSignKeyword_9_1() { return cEqualsSignKeyword_9_1; }

		//route=STRING
		public Assignment getRouteAssignment_9_2() { return cRouteAssignment_9_2; }

		//STRING
		public RuleCall getRouteSTRINGTerminalRuleCall_9_2_0() { return cRouteSTRINGTerminalRuleCall_9_2_0; }

		//";"
		public Keyword getSemicolonKeyword_9_3() { return cSemicolonKeyword_9_3; }

		//("PwSup1" "=" pwSup1=STRING ";")?
		public Group getGroup_10() { return cGroup_10; }

		//"PwSup1"
		public Keyword getPwSup1Keyword_10_0() { return cPwSup1Keyword_10_0; }

		//"="
		public Keyword getEqualsSignKeyword_10_1() { return cEqualsSignKeyword_10_1; }

		//pwSup1=STRING
		public Assignment getPwSup1Assignment_10_2() { return cPwSup1Assignment_10_2; }

		//STRING
		public RuleCall getPwSup1STRINGTerminalRuleCall_10_2_0() { return cPwSup1STRINGTerminalRuleCall_10_2_0; }

		//";"
		public Keyword getSemicolonKeyword_10_3() { return cSemicolonKeyword_10_3; }

		//("EmhZone1" "=" emhZone1=STRING ";")?
		public Group getGroup_11() { return cGroup_11; }

		//"EmhZone1"
		public Keyword getEmhZone1Keyword_11_0() { return cEmhZone1Keyword_11_0; }

		//"="
		public Keyword getEqualsSignKeyword_11_1() { return cEqualsSignKeyword_11_1; }

		//emhZone1=STRING
		public Assignment getEmhZone1Assignment_11_2() { return cEmhZone1Assignment_11_2; }

		//STRING
		public RuleCall getEmhZone1STRINGTerminalRuleCall_11_2_0() { return cEmhZone1STRINGTerminalRuleCall_11_2_0; }

		//";"
		public Keyword getSemicolonKeyword_11_3() { return cSemicolonKeyword_11_3; }

		//("Type" "=" ioType=EqInterfaceType ";")?
		public Group getGroup_12() { return cGroup_12; }

		//"Type"
		public Keyword getTypeKeyword_12_0() { return cTypeKeyword_12_0; }

		//"="
		public Keyword getEqualsSignKeyword_12_1() { return cEqualsSignKeyword_12_1; }

		//ioType=EqInterfaceType
		public Assignment getIoTypeAssignment_12_2() { return cIoTypeAssignment_12_2; }

		//EqInterfaceType
		public RuleCall getIoTypeEqInterfaceTypeEnumRuleCall_12_2_0() { return cIoTypeEqInterfaceTypeEnumRuleCall_12_2_0; }

		//";"
		public Keyword getSemicolonKeyword_12_3() { return cSemicolonKeyword_12_3; }

		//("Generic properties" "{" metricParameters+=MetricParameter* "}")?
		public Group getGroup_13() { return cGroup_13; }

		//"Generic properties"
		public Keyword getGenericPropertiesKeyword_13_0() { return cGenericPropertiesKeyword_13_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_13_1() { return cLeftCurlyBracketKeyword_13_1; }

		//metricParameters+=MetricParameter*
		public Assignment getMetricParametersAssignment_13_2() { return cMetricParametersAssignment_13_2; }

		//MetricParameter
		public RuleCall getMetricParametersMetricParameterParserRuleCall_13_2_0() { return cMetricParametersMetricParameterParserRuleCall_13_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_13_3() { return cRightCurlyBracketKeyword_13_3; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}

	public class DislocalityRelationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "DislocalityRelation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cEqInterfaceGroupAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cEqInterfaceGroupEqInterfaceGroupCrossReference_0_0 = (CrossReference)cEqInterfaceGroupAssignment_0.eContents().get(0);
		private final RuleCall cEqInterfaceGroupEqInterfaceGroupIDTerminalRuleCall_0_0_1 = (RuleCall)cEqInterfaceGroupEqInterfaceGroupCrossReference_0_0.eContents().get(1);
		private final Keyword cDislocalUpToKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cHardwareLevelAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cHardwareLevelHardwareArchitectureLevelTypeEnumRuleCall_2_0 = (RuleCall)cHardwareLevelAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//DislocalityRelation:
		//	eqInterfaceGroup=[EqInterfaceGroup] "dislocal up to" hardwareLevel=HardwareArchitectureLevelType ";";
		public ParserRule getRule() { return rule; }

		//eqInterfaceGroup=[EqInterfaceGroup] "dislocal up to" hardwareLevel=HardwareArchitectureLevelType ";"
		public Group getGroup() { return cGroup; }

		//eqInterfaceGroup=[EqInterfaceGroup]
		public Assignment getEqInterfaceGroupAssignment_0() { return cEqInterfaceGroupAssignment_0; }

		//[EqInterfaceGroup]
		public CrossReference getEqInterfaceGroupEqInterfaceGroupCrossReference_0_0() { return cEqInterfaceGroupEqInterfaceGroupCrossReference_0_0; }

		//ID
		public RuleCall getEqInterfaceGroupEqInterfaceGroupIDTerminalRuleCall_0_0_1() { return cEqInterfaceGroupEqInterfaceGroupIDTerminalRuleCall_0_0_1; }

		//"dislocal up to"
		public Keyword getDislocalUpToKeyword_1() { return cDislocalUpToKeyword_1; }

		//hardwareLevel=HardwareArchitectureLevelType
		public Assignment getHardwareLevelAssignment_2() { return cHardwareLevelAssignment_2; }

		//HardwareArchitectureLevelType
		public RuleCall getHardwareLevelHardwareArchitectureLevelTypeEnumRuleCall_2_0() { return cHardwareLevelHardwareArchitectureLevelTypeEnumRuleCall_2_0; }

		//";"
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}

	public class MetricParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MetricParameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameSTRINGTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueINTTerminalRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		/// *ProximityRelation:
		//	applicationsOrGroups+=[ApplicationOrApplicationGroup] (',' applicationsOrGroups+=[ApplicationOrApplicationGroup])* 'on same' hardwareLevel=HardwareArchitectureLevelType ';'; 
		//
		//CommunicationRelation: 
		//	applicationsOrGroups+=[ApplicationOrApplicationGroup] (',' applicationsOrGroups+=[ApplicationOrApplicationGroup])* 'require' bandwidthUtilization=INT 'bandwidth' ';';
		//	
		//DissimilarityRelation: 
		//	applicationsOrGroups+=[ApplicationOrApplicationGroup] (',' applicationsOrGroups+=[ApplicationOrApplicationGroup])+
		//	'dissimilar based on'
		//	dissimilarityClause=DissimilarityClause ';'
		//;
		//
		//DissimilarityClause:  
		//	DissimilarityEntry | ( '(' (=>DissimilarityDisjunction | DissimilarityConjunction) ')' ) // Der Pfeil ist wichtig!
		//;
		//
		//DissimilarityDisjunction: 
		//	dissimilarityClauses+=DissimilarityClause ( 'OR' dissimilarityClauses+=DissimilarityClause)+ ;
		//
		//DissimilarityConjunction: 
		//	dissimilarityClauses+=DissimilarityClause ( 'AND' dissimilarityClauses+=DissimilarityClause)+ ;
		//
		//DissimilarityEntry: 
		//	( 'Compartment.' compartmentAttribute= CompartmentAttributes ) 	|
		//	( 'Box.' boxAttribute = BoxAttributes) 							|
		//	( 'Board.' boardAttribute = BoardAttributes)					|
		//	( 'Processor.' processorAttribute = ProcessorAttributes)
		//;
		//
		//enum CompartmentAttributes :
		//	MANUFACTURER 	= 'Manufacturer' 	| 
		//	POWERSUPPLY	 	= 'PowerSupply' 	| 
		//	SIDE 		 	= 'Side' 			| 
		//	ZONE		 	= 'Zone';
		//	
		//enum BoxAttributes :
		//	MANUFACTURER 	= 'Manufacturer';
		//	
		//enum BoardAttributes:
		//	MANUFACTURER 	= 'Manufacturer' 			|
		//	POWERSUPPLY 	= 'PowerSupply'				|
		//	ASSURANCELEVEL 	= 'DesignAssuranceLevel' 	|
		//	BOARDTYPE 		= 'Type'	       			|
		//	ESS				= 'ESS'						|
		//	SIDE			= 'Side'; 	
		//
		//enum ProcessorAttributes:
		//	MANUFACTURER 	= 'Manufacturer' 	| 
		//	PROCESSORTYPE	= 'ProcessorType' 
		//;
		// * / MetricParameter:
		//	name=STRING "=" value=INT ";";
		public ParserRule getRule() { return rule; }

		//name=STRING "=" value=INT ";"
		public Group getGroup() { return cGroup; }

		//name=STRING
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_0_0() { return cNameSTRINGTerminalRuleCall_0_0; }

		//"="
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }

		//value=INT
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }

		//INT
		public RuleCall getValueINTTerminalRuleCall_2_0() { return cValueINTTerminalRuleCall_2_0; }

		//";"
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}

	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//	ID ("." ID)*;
		public ParserRule getRule() { return rule; }

		//ID ("." ID)*
		public Group getGroup() { return cGroup; }

		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }

		//("." ID)*
		public Group getGroup_1() { return cGroup_1; }

		//"."
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	
	
	public class HardwareArchitectureLevelTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "HardwareArchitectureLevelType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCOMPARTMENTEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCOMPARTMENTCompartmentKeyword_0_0 = (Keyword)cCOMPARTMENTEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cRDCEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cRDCRDCKeyword_1_0 = (Keyword)cRDCEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cCONNECTOREnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cCONNECTORConnectorKeyword_2_0 = (Keyword)cCONNECTOREnumLiteralDeclaration_2.eContents().get(0);
		
		/// * RELATIONEN * / enum HardwareArchitectureLevelType:
		//	COMPARTMENT="Compartment" | RDC | CONNECTOR="Connector";
		public EnumRule getRule() { return rule; }

		//COMPARTMENT="Compartment" | RDC | CONNECTOR="Connector"
		public Alternatives getAlternatives() { return cAlternatives; }

		//COMPARTMENT="Compartment"
		public EnumLiteralDeclaration getCOMPARTMENTEnumLiteralDeclaration_0() { return cCOMPARTMENTEnumLiteralDeclaration_0; }

		//"Compartment"
		public Keyword getCOMPARTMENTCompartmentKeyword_0_0() { return cCOMPARTMENTCompartmentKeyword_0_0; }

		//RDC
		public EnumLiteralDeclaration getRDCEnumLiteralDeclaration_1() { return cRDCEnumLiteralDeclaration_1; }

		//"RDC"
		public Keyword getRDCRDCKeyword_1_0() { return cRDCRDCKeyword_1_0; }

		//CONNECTOR="Connector"
		public EnumLiteralDeclaration getCONNECTOREnumLiteralDeclaration_2() { return cCONNECTOREnumLiteralDeclaration_2; }

		//"Connector"
		public Keyword getCONNECTORConnectorKeyword_2_0() { return cCONNECTORConnectorKeyword_2_0; }
	}

	public class EqInterfaceTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "EqInterfaceType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCANEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCANCanKeyword_0_0 = (Keyword)cCANEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cELBEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cELBEnhancedLocalBusKeyword_1_0 = (Keyword)cELBEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cETHEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cETHEthernetKeyword_2_0 = (Keyword)cETHEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cANALOGEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cANALOGAnalogKeyword_3_0 = (Keyword)cANALOGEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cDIGITALEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cDIGITALDigitalKeyword_4_0 = (Keyword)cDIGITALEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cSERIALEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cSERIALSerialKeyword_5_0 = (Keyword)cSERIALEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM0EnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cCUSTOM0CustomType0Keyword_6_0 = (Keyword)cCUSTOM0EnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM1EnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cCUSTOM1CustomType1Keyword_7_0 = (Keyword)cCUSTOM1EnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM2EnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cCUSTOM2CustomType2Keyword_8_0 = (Keyword)cCUSTOM2EnumLiteralDeclaration_8.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM3EnumLiteralDeclaration_9 = (EnumLiteralDeclaration)cAlternatives.eContents().get(9);
		private final Keyword cCUSTOM3CustomType3Keyword_9_0 = (Keyword)cCUSTOM3EnumLiteralDeclaration_9.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM4EnumLiteralDeclaration_10 = (EnumLiteralDeclaration)cAlternatives.eContents().get(10);
		private final Keyword cCUSTOM4CustomType4Keyword_10_0 = (Keyword)cCUSTOM4EnumLiteralDeclaration_10.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM5EnumLiteralDeclaration_11 = (EnumLiteralDeclaration)cAlternatives.eContents().get(11);
		private final Keyword cCUSTOM5CustomType5Keyword_11_0 = (Keyword)cCUSTOM5EnumLiteralDeclaration_11.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM6EnumLiteralDeclaration_12 = (EnumLiteralDeclaration)cAlternatives.eContents().get(12);
		private final Keyword cCUSTOM6CustomType6Keyword_12_0 = (Keyword)cCUSTOM6EnumLiteralDeclaration_12.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM7EnumLiteralDeclaration_13 = (EnumLiteralDeclaration)cAlternatives.eContents().get(13);
		private final Keyword cCUSTOM7CustomType7Keyword_13_0 = (Keyword)cCUSTOM7EnumLiteralDeclaration_13.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM8EnumLiteralDeclaration_14 = (EnumLiteralDeclaration)cAlternatives.eContents().get(14);
		private final Keyword cCUSTOM8CustomType8Keyword_14_0 = (Keyword)cCUSTOM8EnumLiteralDeclaration_14.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM9EnumLiteralDeclaration_15 = (EnumLiteralDeclaration)cAlternatives.eContents().get(15);
		private final Keyword cCUSTOM9CustomType9Keyword_15_0 = (Keyword)cCUSTOM9EnumLiteralDeclaration_15.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM10EnumLiteralDeclaration_16 = (EnumLiteralDeclaration)cAlternatives.eContents().get(16);
		private final Keyword cCUSTOM10CustomType10Keyword_16_0 = (Keyword)cCUSTOM10EnumLiteralDeclaration_16.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM11EnumLiteralDeclaration_17 = (EnumLiteralDeclaration)cAlternatives.eContents().get(17);
		private final Keyword cCUSTOM11CustomType11Keyword_17_0 = (Keyword)cCUSTOM11EnumLiteralDeclaration_17.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM12EnumLiteralDeclaration_18 = (EnumLiteralDeclaration)cAlternatives.eContents().get(18);
		private final Keyword cCUSTOM12CustomType12Keyword_18_0 = (Keyword)cCUSTOM12EnumLiteralDeclaration_18.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM13EnumLiteralDeclaration_19 = (EnumLiteralDeclaration)cAlternatives.eContents().get(19);
		private final Keyword cCUSTOM13CustomType13Keyword_19_0 = (Keyword)cCUSTOM13EnumLiteralDeclaration_19.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM14EnumLiteralDeclaration_20 = (EnumLiteralDeclaration)cAlternatives.eContents().get(20);
		private final Keyword cCUSTOM14CustomType14Keyword_20_0 = (Keyword)cCUSTOM14EnumLiteralDeclaration_20.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM15EnumLiteralDeclaration_21 = (EnumLiteralDeclaration)cAlternatives.eContents().get(21);
		private final Keyword cCUSTOM15CustomType15Keyword_21_0 = (Keyword)cCUSTOM15EnumLiteralDeclaration_21.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM16EnumLiteralDeclaration_22 = (EnumLiteralDeclaration)cAlternatives.eContents().get(22);
		private final Keyword cCUSTOM16CustomType16Keyword_22_0 = (Keyword)cCUSTOM16EnumLiteralDeclaration_22.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM17EnumLiteralDeclaration_23 = (EnumLiteralDeclaration)cAlternatives.eContents().get(23);
		private final Keyword cCUSTOM17CustomType17Keyword_23_0 = (Keyword)cCUSTOM17EnumLiteralDeclaration_23.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM18EnumLiteralDeclaration_24 = (EnumLiteralDeclaration)cAlternatives.eContents().get(24);
		private final Keyword cCUSTOM18CustomType18Keyword_24_0 = (Keyword)cCUSTOM18EnumLiteralDeclaration_24.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM19EnumLiteralDeclaration_25 = (EnumLiteralDeclaration)cAlternatives.eContents().get(25);
		private final Keyword cCUSTOM19CustomType19Keyword_25_0 = (Keyword)cCUSTOM19EnumLiteralDeclaration_25.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM20EnumLiteralDeclaration_26 = (EnumLiteralDeclaration)cAlternatives.eContents().get(26);
		private final Keyword cCUSTOM20CustomType20Keyword_26_0 = (Keyword)cCUSTOM20EnumLiteralDeclaration_26.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM21EnumLiteralDeclaration_27 = (EnumLiteralDeclaration)cAlternatives.eContents().get(27);
		private final Keyword cCUSTOM21CustomType21Keyword_27_0 = (Keyword)cCUSTOM21EnumLiteralDeclaration_27.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM22EnumLiteralDeclaration_28 = (EnumLiteralDeclaration)cAlternatives.eContents().get(28);
		private final Keyword cCUSTOM22CustomType22Keyword_28_0 = (Keyword)cCUSTOM22EnumLiteralDeclaration_28.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM23EnumLiteralDeclaration_29 = (EnumLiteralDeclaration)cAlternatives.eContents().get(29);
		private final Keyword cCUSTOM23CustomType23Keyword_29_0 = (Keyword)cCUSTOM23EnumLiteralDeclaration_29.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM24EnumLiteralDeclaration_30 = (EnumLiteralDeclaration)cAlternatives.eContents().get(30);
		private final Keyword cCUSTOM24CustomType24Keyword_30_0 = (Keyword)cCUSTOM24EnumLiteralDeclaration_30.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM25EnumLiteralDeclaration_31 = (EnumLiteralDeclaration)cAlternatives.eContents().get(31);
		private final Keyword cCUSTOM25CustomType25Keyword_31_0 = (Keyword)cCUSTOM25EnumLiteralDeclaration_31.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM26EnumLiteralDeclaration_32 = (EnumLiteralDeclaration)cAlternatives.eContents().get(32);
		private final Keyword cCUSTOM26CustomType26Keyword_32_0 = (Keyword)cCUSTOM26EnumLiteralDeclaration_32.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM27EnumLiteralDeclaration_33 = (EnumLiteralDeclaration)cAlternatives.eContents().get(33);
		private final Keyword cCUSTOM27CustomType27Keyword_33_0 = (Keyword)cCUSTOM27EnumLiteralDeclaration_33.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM28EnumLiteralDeclaration_34 = (EnumLiteralDeclaration)cAlternatives.eContents().get(34);
		private final Keyword cCUSTOM28CustomType28Keyword_34_0 = (Keyword)cCUSTOM28EnumLiteralDeclaration_34.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM29EnumLiteralDeclaration_35 = (EnumLiteralDeclaration)cAlternatives.eContents().get(35);
		private final Keyword cCUSTOM29CustomType29Keyword_35_0 = (Keyword)cCUSTOM29EnumLiteralDeclaration_35.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM30EnumLiteralDeclaration_36 = (EnumLiteralDeclaration)cAlternatives.eContents().get(36);
		private final Keyword cCUSTOM30CustomType30Keyword_36_0 = (Keyword)cCUSTOM30EnumLiteralDeclaration_36.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM31EnumLiteralDeclaration_37 = (EnumLiteralDeclaration)cAlternatives.eContents().get(37);
		private final Keyword cCUSTOM31CustomType31Keyword_37_0 = (Keyword)cCUSTOM31EnumLiteralDeclaration_37.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM32EnumLiteralDeclaration_38 = (EnumLiteralDeclaration)cAlternatives.eContents().get(38);
		private final Keyword cCUSTOM32CustomType32Keyword_38_0 = (Keyword)cCUSTOM32EnumLiteralDeclaration_38.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM33EnumLiteralDeclaration_39 = (EnumLiteralDeclaration)cAlternatives.eContents().get(39);
		private final Keyword cCUSTOM33CustomType33Keyword_39_0 = (Keyword)cCUSTOM33EnumLiteralDeclaration_39.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM34EnumLiteralDeclaration_40 = (EnumLiteralDeclaration)cAlternatives.eContents().get(40);
		private final Keyword cCUSTOM34CustomType34Keyword_40_0 = (Keyword)cCUSTOM34EnumLiteralDeclaration_40.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM35EnumLiteralDeclaration_41 = (EnumLiteralDeclaration)cAlternatives.eContents().get(41);
		private final Keyword cCUSTOM35CustomType35Keyword_41_0 = (Keyword)cCUSTOM35EnumLiteralDeclaration_41.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM36EnumLiteralDeclaration_42 = (EnumLiteralDeclaration)cAlternatives.eContents().get(42);
		private final Keyword cCUSTOM36CustomType36Keyword_42_0 = (Keyword)cCUSTOM36EnumLiteralDeclaration_42.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM37EnumLiteralDeclaration_43 = (EnumLiteralDeclaration)cAlternatives.eContents().get(43);
		private final Keyword cCUSTOM37CustomType37Keyword_43_0 = (Keyword)cCUSTOM37EnumLiteralDeclaration_43.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM38EnumLiteralDeclaration_44 = (EnumLiteralDeclaration)cAlternatives.eContents().get(44);
		private final Keyword cCUSTOM38CustomType38Keyword_44_0 = (Keyword)cCUSTOM38EnumLiteralDeclaration_44.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOM39EnumLiteralDeclaration_45 = (EnumLiteralDeclaration)cAlternatives.eContents().get(45);
		private final Keyword cCUSTOM39CustomType39Keyword_45_0 = (Keyword)cCUSTOM39EnumLiteralDeclaration_45.eContents().get(0);
		
		/// * ENUMS * / enum EqInterfaceType:
		//	CAN="Can" | ELB="Enhanced Local Bus" | ETH="Ethernet" | ANALOG="Analog" | DIGITAL="Digital" | SERIAL="Serial" |
		//	CUSTOM0="CustomType0" | CUSTOM1="CustomType1" | CUSTOM2="CustomType2" | CUSTOM3="CustomType3" | CUSTOM4="CustomType4"
		//	| CUSTOM5="CustomType5" | CUSTOM6="CustomType6" | CUSTOM7="CustomType7" | CUSTOM8="CustomType8" |
		//	CUSTOM9="CustomType9" | CUSTOM10="CustomType10" | CUSTOM11="CustomType11" | CUSTOM12="CustomType12" |
		//	CUSTOM13="CustomType13" | CUSTOM14="CustomType14" | CUSTOM15="CustomType15" | CUSTOM16="CustomType16" |
		//	CUSTOM17="CustomType17" | CUSTOM18="CustomType18" | CUSTOM19="CustomType19" | CUSTOM20="CustomType20" |
		//	CUSTOM21="CustomType21" | CUSTOM22="CustomType22" | CUSTOM23="CustomType23" | CUSTOM24="CustomType24" |
		//	CUSTOM25="CustomType25" | CUSTOM26="CustomType26" | CUSTOM27="CustomType27" | CUSTOM28="CustomType28" |
		//	CUSTOM29="CustomType29" | CUSTOM30="CustomType30" | CUSTOM31="CustomType31" | CUSTOM32="CustomType32" |
		//	CUSTOM33="CustomType33" | CUSTOM34="CustomType34" | CUSTOM35="CustomType35" | CUSTOM36="CustomType36" |
		//	CUSTOM37="CustomType37" | CUSTOM38="CustomType38" | CUSTOM39="CustomType39";
		public EnumRule getRule() { return rule; }

		//CAN="Can" | ELB="Enhanced Local Bus" | ETH="Ethernet" | ANALOG="Analog" | DIGITAL="Digital" | SERIAL="Serial" |
		//CUSTOM0="CustomType0" | CUSTOM1="CustomType1" | CUSTOM2="CustomType2" | CUSTOM3="CustomType3" | CUSTOM4="CustomType4"
		//| CUSTOM5="CustomType5" | CUSTOM6="CustomType6" | CUSTOM7="CustomType7" | CUSTOM8="CustomType8" |
		//CUSTOM9="CustomType9" | CUSTOM10="CustomType10" | CUSTOM11="CustomType11" | CUSTOM12="CustomType12" |
		//CUSTOM13="CustomType13" | CUSTOM14="CustomType14" | CUSTOM15="CustomType15" | CUSTOM16="CustomType16" |
		//CUSTOM17="CustomType17" | CUSTOM18="CustomType18" | CUSTOM19="CustomType19" | CUSTOM20="CustomType20" |
		//CUSTOM21="CustomType21" | CUSTOM22="CustomType22" | CUSTOM23="CustomType23" | CUSTOM24="CustomType24" |
		//CUSTOM25="CustomType25" | CUSTOM26="CustomType26" | CUSTOM27="CustomType27" | CUSTOM28="CustomType28" |
		//CUSTOM29="CustomType29" | CUSTOM30="CustomType30" | CUSTOM31="CustomType31" | CUSTOM32="CustomType32" |
		//CUSTOM33="CustomType33" | CUSTOM34="CustomType34" | CUSTOM35="CustomType35" | CUSTOM36="CustomType36" |
		//CUSTOM37="CustomType37" | CUSTOM38="CustomType38" | CUSTOM39="CustomType39"
		public Alternatives getAlternatives() { return cAlternatives; }

		//CAN="Can"
		public EnumLiteralDeclaration getCANEnumLiteralDeclaration_0() { return cCANEnumLiteralDeclaration_0; }

		//"Can"
		public Keyword getCANCanKeyword_0_0() { return cCANCanKeyword_0_0; }

		//ELB="Enhanced Local Bus"
		public EnumLiteralDeclaration getELBEnumLiteralDeclaration_1() { return cELBEnumLiteralDeclaration_1; }

		//"Enhanced Local Bus"
		public Keyword getELBEnhancedLocalBusKeyword_1_0() { return cELBEnhancedLocalBusKeyword_1_0; }

		//ETH="Ethernet"
		public EnumLiteralDeclaration getETHEnumLiteralDeclaration_2() { return cETHEnumLiteralDeclaration_2; }

		//"Ethernet"
		public Keyword getETHEthernetKeyword_2_0() { return cETHEthernetKeyword_2_0; }

		//ANALOG="Analog"
		public EnumLiteralDeclaration getANALOGEnumLiteralDeclaration_3() { return cANALOGEnumLiteralDeclaration_3; }

		//"Analog"
		public Keyword getANALOGAnalogKeyword_3_0() { return cANALOGAnalogKeyword_3_0; }

		//DIGITAL="Digital"
		public EnumLiteralDeclaration getDIGITALEnumLiteralDeclaration_4() { return cDIGITALEnumLiteralDeclaration_4; }

		//"Digital"
		public Keyword getDIGITALDigitalKeyword_4_0() { return cDIGITALDigitalKeyword_4_0; }

		//SERIAL="Serial"
		public EnumLiteralDeclaration getSERIALEnumLiteralDeclaration_5() { return cSERIALEnumLiteralDeclaration_5; }

		//"Serial"
		public Keyword getSERIALSerialKeyword_5_0() { return cSERIALSerialKeyword_5_0; }

		//CUSTOM0="CustomType0"
		public EnumLiteralDeclaration getCUSTOM0EnumLiteralDeclaration_6() { return cCUSTOM0EnumLiteralDeclaration_6; }

		//"CustomType0"
		public Keyword getCUSTOM0CustomType0Keyword_6_0() { return cCUSTOM0CustomType0Keyword_6_0; }

		//CUSTOM1="CustomType1"
		public EnumLiteralDeclaration getCUSTOM1EnumLiteralDeclaration_7() { return cCUSTOM1EnumLiteralDeclaration_7; }

		//"CustomType1"
		public Keyword getCUSTOM1CustomType1Keyword_7_0() { return cCUSTOM1CustomType1Keyword_7_0; }

		//CUSTOM2="CustomType2"
		public EnumLiteralDeclaration getCUSTOM2EnumLiteralDeclaration_8() { return cCUSTOM2EnumLiteralDeclaration_8; }

		//"CustomType2"
		public Keyword getCUSTOM2CustomType2Keyword_8_0() { return cCUSTOM2CustomType2Keyword_8_0; }

		//CUSTOM3="CustomType3"
		public EnumLiteralDeclaration getCUSTOM3EnumLiteralDeclaration_9() { return cCUSTOM3EnumLiteralDeclaration_9; }

		//"CustomType3"
		public Keyword getCUSTOM3CustomType3Keyword_9_0() { return cCUSTOM3CustomType3Keyword_9_0; }

		//CUSTOM4="CustomType4"
		public EnumLiteralDeclaration getCUSTOM4EnumLiteralDeclaration_10() { return cCUSTOM4EnumLiteralDeclaration_10; }

		//"CustomType4"
		public Keyword getCUSTOM4CustomType4Keyword_10_0() { return cCUSTOM4CustomType4Keyword_10_0; }

		//CUSTOM5="CustomType5"
		public EnumLiteralDeclaration getCUSTOM5EnumLiteralDeclaration_11() { return cCUSTOM5EnumLiteralDeclaration_11; }

		//"CustomType5"
		public Keyword getCUSTOM5CustomType5Keyword_11_0() { return cCUSTOM5CustomType5Keyword_11_0; }

		//CUSTOM6="CustomType6"
		public EnumLiteralDeclaration getCUSTOM6EnumLiteralDeclaration_12() { return cCUSTOM6EnumLiteralDeclaration_12; }

		//"CustomType6"
		public Keyword getCUSTOM6CustomType6Keyword_12_0() { return cCUSTOM6CustomType6Keyword_12_0; }

		//CUSTOM7="CustomType7"
		public EnumLiteralDeclaration getCUSTOM7EnumLiteralDeclaration_13() { return cCUSTOM7EnumLiteralDeclaration_13; }

		//"CustomType7"
		public Keyword getCUSTOM7CustomType7Keyword_13_0() { return cCUSTOM7CustomType7Keyword_13_0; }

		//CUSTOM8="CustomType8"
		public EnumLiteralDeclaration getCUSTOM8EnumLiteralDeclaration_14() { return cCUSTOM8EnumLiteralDeclaration_14; }

		//"CustomType8"
		public Keyword getCUSTOM8CustomType8Keyword_14_0() { return cCUSTOM8CustomType8Keyword_14_0; }

		//CUSTOM9="CustomType9"
		public EnumLiteralDeclaration getCUSTOM9EnumLiteralDeclaration_15() { return cCUSTOM9EnumLiteralDeclaration_15; }

		//"CustomType9"
		public Keyword getCUSTOM9CustomType9Keyword_15_0() { return cCUSTOM9CustomType9Keyword_15_0; }

		//CUSTOM10="CustomType10"
		public EnumLiteralDeclaration getCUSTOM10EnumLiteralDeclaration_16() { return cCUSTOM10EnumLiteralDeclaration_16; }

		//"CustomType10"
		public Keyword getCUSTOM10CustomType10Keyword_16_0() { return cCUSTOM10CustomType10Keyword_16_0; }

		//CUSTOM11="CustomType11"
		public EnumLiteralDeclaration getCUSTOM11EnumLiteralDeclaration_17() { return cCUSTOM11EnumLiteralDeclaration_17; }

		//"CustomType11"
		public Keyword getCUSTOM11CustomType11Keyword_17_0() { return cCUSTOM11CustomType11Keyword_17_0; }

		//CUSTOM12="CustomType12"
		public EnumLiteralDeclaration getCUSTOM12EnumLiteralDeclaration_18() { return cCUSTOM12EnumLiteralDeclaration_18; }

		//"CustomType12"
		public Keyword getCUSTOM12CustomType12Keyword_18_0() { return cCUSTOM12CustomType12Keyword_18_0; }

		//CUSTOM13="CustomType13"
		public EnumLiteralDeclaration getCUSTOM13EnumLiteralDeclaration_19() { return cCUSTOM13EnumLiteralDeclaration_19; }

		//"CustomType13"
		public Keyword getCUSTOM13CustomType13Keyword_19_0() { return cCUSTOM13CustomType13Keyword_19_0; }

		//CUSTOM14="CustomType14"
		public EnumLiteralDeclaration getCUSTOM14EnumLiteralDeclaration_20() { return cCUSTOM14EnumLiteralDeclaration_20; }

		//"CustomType14"
		public Keyword getCUSTOM14CustomType14Keyword_20_0() { return cCUSTOM14CustomType14Keyword_20_0; }

		//CUSTOM15="CustomType15"
		public EnumLiteralDeclaration getCUSTOM15EnumLiteralDeclaration_21() { return cCUSTOM15EnumLiteralDeclaration_21; }

		//"CustomType15"
		public Keyword getCUSTOM15CustomType15Keyword_21_0() { return cCUSTOM15CustomType15Keyword_21_0; }

		//CUSTOM16="CustomType16"
		public EnumLiteralDeclaration getCUSTOM16EnumLiteralDeclaration_22() { return cCUSTOM16EnumLiteralDeclaration_22; }

		//"CustomType16"
		public Keyword getCUSTOM16CustomType16Keyword_22_0() { return cCUSTOM16CustomType16Keyword_22_0; }

		//CUSTOM17="CustomType17"
		public EnumLiteralDeclaration getCUSTOM17EnumLiteralDeclaration_23() { return cCUSTOM17EnumLiteralDeclaration_23; }

		//"CustomType17"
		public Keyword getCUSTOM17CustomType17Keyword_23_0() { return cCUSTOM17CustomType17Keyword_23_0; }

		//CUSTOM18="CustomType18"
		public EnumLiteralDeclaration getCUSTOM18EnumLiteralDeclaration_24() { return cCUSTOM18EnumLiteralDeclaration_24; }

		//"CustomType18"
		public Keyword getCUSTOM18CustomType18Keyword_24_0() { return cCUSTOM18CustomType18Keyword_24_0; }

		//CUSTOM19="CustomType19"
		public EnumLiteralDeclaration getCUSTOM19EnumLiteralDeclaration_25() { return cCUSTOM19EnumLiteralDeclaration_25; }

		//"CustomType19"
		public Keyword getCUSTOM19CustomType19Keyword_25_0() { return cCUSTOM19CustomType19Keyword_25_0; }

		//CUSTOM20="CustomType20"
		public EnumLiteralDeclaration getCUSTOM20EnumLiteralDeclaration_26() { return cCUSTOM20EnumLiteralDeclaration_26; }

		//"CustomType20"
		public Keyword getCUSTOM20CustomType20Keyword_26_0() { return cCUSTOM20CustomType20Keyword_26_0; }

		//CUSTOM21="CustomType21"
		public EnumLiteralDeclaration getCUSTOM21EnumLiteralDeclaration_27() { return cCUSTOM21EnumLiteralDeclaration_27; }

		//"CustomType21"
		public Keyword getCUSTOM21CustomType21Keyword_27_0() { return cCUSTOM21CustomType21Keyword_27_0; }

		//CUSTOM22="CustomType22"
		public EnumLiteralDeclaration getCUSTOM22EnumLiteralDeclaration_28() { return cCUSTOM22EnumLiteralDeclaration_28; }

		//"CustomType22"
		public Keyword getCUSTOM22CustomType22Keyword_28_0() { return cCUSTOM22CustomType22Keyword_28_0; }

		//CUSTOM23="CustomType23"
		public EnumLiteralDeclaration getCUSTOM23EnumLiteralDeclaration_29() { return cCUSTOM23EnumLiteralDeclaration_29; }

		//"CustomType23"
		public Keyword getCUSTOM23CustomType23Keyword_29_0() { return cCUSTOM23CustomType23Keyword_29_0; }

		//CUSTOM24="CustomType24"
		public EnumLiteralDeclaration getCUSTOM24EnumLiteralDeclaration_30() { return cCUSTOM24EnumLiteralDeclaration_30; }

		//"CustomType24"
		public Keyword getCUSTOM24CustomType24Keyword_30_0() { return cCUSTOM24CustomType24Keyword_30_0; }

		//CUSTOM25="CustomType25"
		public EnumLiteralDeclaration getCUSTOM25EnumLiteralDeclaration_31() { return cCUSTOM25EnumLiteralDeclaration_31; }

		//"CustomType25"
		public Keyword getCUSTOM25CustomType25Keyword_31_0() { return cCUSTOM25CustomType25Keyword_31_0; }

		//CUSTOM26="CustomType26"
		public EnumLiteralDeclaration getCUSTOM26EnumLiteralDeclaration_32() { return cCUSTOM26EnumLiteralDeclaration_32; }

		//"CustomType26"
		public Keyword getCUSTOM26CustomType26Keyword_32_0() { return cCUSTOM26CustomType26Keyword_32_0; }

		//CUSTOM27="CustomType27"
		public EnumLiteralDeclaration getCUSTOM27EnumLiteralDeclaration_33() { return cCUSTOM27EnumLiteralDeclaration_33; }

		//"CustomType27"
		public Keyword getCUSTOM27CustomType27Keyword_33_0() { return cCUSTOM27CustomType27Keyword_33_0; }

		//CUSTOM28="CustomType28"
		public EnumLiteralDeclaration getCUSTOM28EnumLiteralDeclaration_34() { return cCUSTOM28EnumLiteralDeclaration_34; }

		//"CustomType28"
		public Keyword getCUSTOM28CustomType28Keyword_34_0() { return cCUSTOM28CustomType28Keyword_34_0; }

		//CUSTOM29="CustomType29"
		public EnumLiteralDeclaration getCUSTOM29EnumLiteralDeclaration_35() { return cCUSTOM29EnumLiteralDeclaration_35; }

		//"CustomType29"
		public Keyword getCUSTOM29CustomType29Keyword_35_0() { return cCUSTOM29CustomType29Keyword_35_0; }

		//CUSTOM30="CustomType30"
		public EnumLiteralDeclaration getCUSTOM30EnumLiteralDeclaration_36() { return cCUSTOM30EnumLiteralDeclaration_36; }

		//"CustomType30"
		public Keyword getCUSTOM30CustomType30Keyword_36_0() { return cCUSTOM30CustomType30Keyword_36_0; }

		//CUSTOM31="CustomType31"
		public EnumLiteralDeclaration getCUSTOM31EnumLiteralDeclaration_37() { return cCUSTOM31EnumLiteralDeclaration_37; }

		//"CustomType31"
		public Keyword getCUSTOM31CustomType31Keyword_37_0() { return cCUSTOM31CustomType31Keyword_37_0; }

		//CUSTOM32="CustomType32"
		public EnumLiteralDeclaration getCUSTOM32EnumLiteralDeclaration_38() { return cCUSTOM32EnumLiteralDeclaration_38; }

		//"CustomType32"
		public Keyword getCUSTOM32CustomType32Keyword_38_0() { return cCUSTOM32CustomType32Keyword_38_0; }

		//CUSTOM33="CustomType33"
		public EnumLiteralDeclaration getCUSTOM33EnumLiteralDeclaration_39() { return cCUSTOM33EnumLiteralDeclaration_39; }

		//"CustomType33"
		public Keyword getCUSTOM33CustomType33Keyword_39_0() { return cCUSTOM33CustomType33Keyword_39_0; }

		//CUSTOM34="CustomType34"
		public EnumLiteralDeclaration getCUSTOM34EnumLiteralDeclaration_40() { return cCUSTOM34EnumLiteralDeclaration_40; }

		//"CustomType34"
		public Keyword getCUSTOM34CustomType34Keyword_40_0() { return cCUSTOM34CustomType34Keyword_40_0; }

		//CUSTOM35="CustomType35"
		public EnumLiteralDeclaration getCUSTOM35EnumLiteralDeclaration_41() { return cCUSTOM35EnumLiteralDeclaration_41; }

		//"CustomType35"
		public Keyword getCUSTOM35CustomType35Keyword_41_0() { return cCUSTOM35CustomType35Keyword_41_0; }

		//CUSTOM36="CustomType36"
		public EnumLiteralDeclaration getCUSTOM36EnumLiteralDeclaration_42() { return cCUSTOM36EnumLiteralDeclaration_42; }

		//"CustomType36"
		public Keyword getCUSTOM36CustomType36Keyword_42_0() { return cCUSTOM36CustomType36Keyword_42_0; }

		//CUSTOM37="CustomType37"
		public EnumLiteralDeclaration getCUSTOM37EnumLiteralDeclaration_43() { return cCUSTOM37EnumLiteralDeclaration_43; }

		//"CustomType37"
		public Keyword getCUSTOM37CustomType37Keyword_43_0() { return cCUSTOM37CustomType37Keyword_43_0; }

		//CUSTOM38="CustomType38"
		public EnumLiteralDeclaration getCUSTOM38EnumLiteralDeclaration_44() { return cCUSTOM38EnumLiteralDeclaration_44; }

		//"CustomType38"
		public Keyword getCUSTOM38CustomType38Keyword_44_0() { return cCUSTOM38CustomType38Keyword_44_0; }

		//CUSTOM39="CustomType39"
		public EnumLiteralDeclaration getCUSTOM39EnumLiteralDeclaration_45() { return cCUSTOM39EnumLiteralDeclaration_45; }

		//"CustomType39"
		public Keyword getCUSTOM39CustomType39Keyword_45_0() { return cCUSTOM39CustomType39Keyword_45_0; }
	}
	
	private final AssistModelElements pAssistModel;
	private final CompartmentElements pCompartment;
	private final RDCElements pRDC;
	private final ConnectorElements pConnector;
	private final AvailableEqInterfaceElements pAvailableEqInterface;
	private final EqInterfaceGroupElements pEqInterfaceGroup;
	private final EqInterfaceElements pEqInterface;
	private final HardwareArchitectureLevelTypeElements unknownRuleHardwareArchitectureLevelType;
	private final DislocalityRelationElements pDislocalityRelation;
	private final MetricParameterElements pMetricParameter;
	private final QualifiedNameElements pQualifiedName;
	private final EqInterfaceTypeElements unknownRuleEqInterfaceType;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MappingDSLGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pAssistModel = new AssistModelElements();
		this.pCompartment = new CompartmentElements();
		this.pRDC = new RDCElements();
		this.pConnector = new ConnectorElements();
		this.pAvailableEqInterface = new AvailableEqInterfaceElements();
		this.pEqInterfaceGroup = new EqInterfaceGroupElements();
		this.pEqInterface = new EqInterfaceElements();
		this.unknownRuleHardwareArchitectureLevelType = new HardwareArchitectureLevelTypeElements();
		this.pDislocalityRelation = new DislocalityRelationElements();
		this.pMetricParameter = new MetricParameterElements();
		this.pQualifiedName = new QualifiedNameElements();
		this.unknownRuleEqInterfaceType = new EqInterfaceTypeElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("ch.hilbri.assist.mappingdsl.MappingDSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//AssistModel:
	//	"Global" "{" "System name" "=" systemName=STRING ";" "}" compartments+=Compartment? ("Interfaces" "{"
	//	eqInterfaces+=EqInterface+ "}")? ("InterfaceGroups" "{" eqInterfaceGroups+=EqInterfaceGroup+ "}")? ("Restrictions"
	//	"{" dislocalityRelations+=DislocalityRelation* "}")?;
	public AssistModelElements getAssistModelAccess() {
		return pAssistModel;
	}
	
	public ParserRule getAssistModelRule() {
		return getAssistModelAccess().getRule();
	}

	//Compartment:
	//	"Compartment" name=ID "{" (("Manufacturer" "=" manufacturer=STRING ";")? & ("PowerSupply" "=" powerSupply=STRING
	//	";")? & ("Side" "=" side=STRING ";")? & ("Zone" "=" zone=STRING ";")? & rdcs+=RDC*) "}";
	public CompartmentElements getCompartmentAccess() {
		return pCompartment;
	}
	
	public ParserRule getCompartmentRule() {
		return getCompartmentAccess().getRule();
	}

	//RDC:
	//	"RDC" name=ID "{" ("Manufacturer" "=" manufacturer=STRING ";")? ("PowerSupply" "=" powerSupply=STRING ";")? ("Type"
	//	"=" rdcType=STRING ";")? ("ESS" "=" ess=STRING ";")? connectors+=Connector+ ("Generic properties" "{"
	//	metricParameters+=MetricParameter* "}")? "}";
	public RDCElements getRDCAccess() {
		return pRDC;
	}
	
	public ParserRule getRDCRule() {
		return getRDCAccess().getRule();
	}

	//Connector:
	//	"Connector" name=ID "{" availableEqInterfaces+=AvailableEqInterface* "}";
	public ConnectorElements getConnectorAccess() {
		return pConnector;
	}
	
	public ParserRule getConnectorRule() {
		return getConnectorAccess().getRule();
	}

	//AvailableEqInterface:
	//	count=INT "interface with type" eqInterfaceType=EqInterfaceType ";";
	public AvailableEqInterfaceElements getAvailableEqInterfaceAccess() {
		return pAvailableEqInterface;
	}
	
	public ParserRule getAvailableEqInterfaceRule() {
		return getAvailableEqInterfaceAccess().getRule();
	}

	/// * SOFTWARE * / EqInterfaceGroup:
	//	"Group" name=ID "{" eqInterfaces+=[EqInterface] ("," eqInterfaces+=[EqInterface])+ "}";
	public EqInterfaceGroupElements getEqInterfaceGroupAccess() {
		return pEqInterfaceGroup;
	}
	
	public ParserRule getEqInterfaceGroupRule() {
		return getEqInterfaceGroupAccess().getRule();
	}

	//EqInterface:
	//	"Interface" name=ID "{" ("InterfaceSystem" "=" system=STRING ";")? ("SubAta" "=" subAta=STRING ";")? ("Resource" "="
	//	resource=STRING ";")? ("LineName" "=" lineName=STRING ";")? ("WiringLane" "=" wiringLane=STRING ";")? ("GrpInfo" "="
	//	grpInfo=STRING ";")? ("Route" "=" route=STRING ";")? ("PwSup1" "=" pwSup1=STRING ";")? ("EmhZone1" "="
	//	emhZone1=STRING ";")? ("Type" "=" ioType=EqInterfaceType ";")? ("Generic properties" "{"
	//	metricParameters+=MetricParameter* "}")? "}";
	public EqInterfaceElements getEqInterfaceAccess() {
		return pEqInterface;
	}
	
	public ParserRule getEqInterfaceRule() {
		return getEqInterfaceAccess().getRule();
	}

	/// * RELATIONEN * / enum HardwareArchitectureLevelType:
	//	COMPARTMENT="Compartment" | RDC | CONNECTOR="Connector";
	public HardwareArchitectureLevelTypeElements getHardwareArchitectureLevelTypeAccess() {
		return unknownRuleHardwareArchitectureLevelType;
	}
	
	public EnumRule getHardwareArchitectureLevelTypeRule() {
		return getHardwareArchitectureLevelTypeAccess().getRule();
	}

	//DislocalityRelation:
	//	eqInterfaceGroup=[EqInterfaceGroup] "dislocal up to" hardwareLevel=HardwareArchitectureLevelType ";";
	public DislocalityRelationElements getDislocalityRelationAccess() {
		return pDislocalityRelation;
	}
	
	public ParserRule getDislocalityRelationRule() {
		return getDislocalityRelationAccess().getRule();
	}

	/// *ProximityRelation:
	//	applicationsOrGroups+=[ApplicationOrApplicationGroup] (',' applicationsOrGroups+=[ApplicationOrApplicationGroup])* 'on same' hardwareLevel=HardwareArchitectureLevelType ';'; 
	//
	//CommunicationRelation: 
	//	applicationsOrGroups+=[ApplicationOrApplicationGroup] (',' applicationsOrGroups+=[ApplicationOrApplicationGroup])* 'require' bandwidthUtilization=INT 'bandwidth' ';';
	//	
	//DissimilarityRelation: 
	//	applicationsOrGroups+=[ApplicationOrApplicationGroup] (',' applicationsOrGroups+=[ApplicationOrApplicationGroup])+
	//	'dissimilar based on'
	//	dissimilarityClause=DissimilarityClause ';'
	//;
	//
	//DissimilarityClause:  
	//	DissimilarityEntry | ( '(' (=>DissimilarityDisjunction | DissimilarityConjunction) ')' ) // Der Pfeil ist wichtig!
	//;
	//
	//DissimilarityDisjunction: 
	//	dissimilarityClauses+=DissimilarityClause ( 'OR' dissimilarityClauses+=DissimilarityClause)+ ;
	//
	//DissimilarityConjunction: 
	//	dissimilarityClauses+=DissimilarityClause ( 'AND' dissimilarityClauses+=DissimilarityClause)+ ;
	//
	//DissimilarityEntry: 
	//	( 'Compartment.' compartmentAttribute= CompartmentAttributes ) 	|
	//	( 'Box.' boxAttribute = BoxAttributes) 							|
	//	( 'Board.' boardAttribute = BoardAttributes)					|
	//	( 'Processor.' processorAttribute = ProcessorAttributes)
	//;
	//
	//enum CompartmentAttributes :
	//	MANUFACTURER 	= 'Manufacturer' 	| 
	//	POWERSUPPLY	 	= 'PowerSupply' 	| 
	//	SIDE 		 	= 'Side' 			| 
	//	ZONE		 	= 'Zone';
	//	
	//enum BoxAttributes :
	//	MANUFACTURER 	= 'Manufacturer';
	//	
	//enum BoardAttributes:
	//	MANUFACTURER 	= 'Manufacturer' 			|
	//	POWERSUPPLY 	= 'PowerSupply'				|
	//	ASSURANCELEVEL 	= 'DesignAssuranceLevel' 	|
	//	BOARDTYPE 		= 'Type'	       			|
	//	ESS				= 'ESS'						|
	//	SIDE			= 'Side'; 	
	//
	//enum ProcessorAttributes:
	//	MANUFACTURER 	= 'Manufacturer' 	| 
	//	PROCESSORTYPE	= 'ProcessorType' 
	//;
	// * / MetricParameter:
	//	name=STRING "=" value=INT ";";
	public MetricParameterElements getMetricParameterAccess() {
		return pMetricParameter;
	}
	
	public ParserRule getMetricParameterRule() {
		return getMetricParameterAccess().getRule();
	}

	//QualifiedName:
	//	ID ("." ID)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return pQualifiedName;
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	/// * ENUMS * / enum EqInterfaceType:
	//	CAN="Can" | ELB="Enhanced Local Bus" | ETH="Ethernet" | ANALOG="Analog" | DIGITAL="Digital" | SERIAL="Serial" |
	//	CUSTOM0="CustomType0" | CUSTOM1="CustomType1" | CUSTOM2="CustomType2" | CUSTOM3="CustomType3" | CUSTOM4="CustomType4"
	//	| CUSTOM5="CustomType5" | CUSTOM6="CustomType6" | CUSTOM7="CustomType7" | CUSTOM8="CustomType8" |
	//	CUSTOM9="CustomType9" | CUSTOM10="CustomType10" | CUSTOM11="CustomType11" | CUSTOM12="CustomType12" |
	//	CUSTOM13="CustomType13" | CUSTOM14="CustomType14" | CUSTOM15="CustomType15" | CUSTOM16="CustomType16" |
	//	CUSTOM17="CustomType17" | CUSTOM18="CustomType18" | CUSTOM19="CustomType19" | CUSTOM20="CustomType20" |
	//	CUSTOM21="CustomType21" | CUSTOM22="CustomType22" | CUSTOM23="CustomType23" | CUSTOM24="CustomType24" |
	//	CUSTOM25="CustomType25" | CUSTOM26="CustomType26" | CUSTOM27="CustomType27" | CUSTOM28="CustomType28" |
	//	CUSTOM29="CustomType29" | CUSTOM30="CustomType30" | CUSTOM31="CustomType31" | CUSTOM32="CustomType32" |
	//	CUSTOM33="CustomType33" | CUSTOM34="CustomType34" | CUSTOM35="CustomType35" | CUSTOM36="CustomType36" |
	//	CUSTOM37="CustomType37" | CUSTOM38="CustomType38" | CUSTOM39="CustomType39";
	public EqInterfaceTypeElements getEqInterfaceTypeAccess() {
		return unknownRuleEqInterfaceType;
	}
	
	public EnumRule getEqInterfaceTypeRule() {
		return getEqInterfaceTypeAccess().getRule();
	}

	//terminal ID returns ecore::EString:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING returns ecore::EString:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT returns ecore::EString:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT returns ecore::EString:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS returns ecore::EString:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER returns ecore::EString:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
