/*
 * generated by Xtext 2.12.0
 */
package ch.hilbri.assist.scheduling.dsl.ide


/**
 * Use this class to register ide components.
 */
class SchedulingDslIdeModule extends AbstractSchedulingDslIdeModule {
}
