/*
 * generated by Xtext
 */
package ch.hilbri.assist.schedulingdsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SchedulingDSLRuntimeModule extends ch.hilbri.assist.schedulingdsl.AbstractSchedulingDSLRuntimeModule {

}
