/*
* generated by Xtext
*/
package ch.hilbri.assist.schedulingdsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SchedulingDSLStandaloneSetup extends SchedulingDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new SchedulingDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

