package ch.hilbri.assist.mapping.solver;

public enum SearchType {
	DEFAULT,
	MIN_DOMAIN_FIRST,
	MAX_DEGREE_FIRST,
	HARDEST_DISLOCALITIES_FIRST,
	SCARCEST_IOTYPE_FIRST,
	VARS_IN_MOST_DISLOC,
	DOM_OVER_WDEG,
	ACTIVITY,
	IMPACT,
	RANDOM
}
