/*
* generated by Xtext
*/
package ch.hilbri.assist.mappingdsl;

public class MappingDSLStandaloneSetup extends MappingDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new MappingDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

