/*
 * generated by Xtext
 */
package ch.hilbri.assist.mappingdsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MappingDSLRuntimeModule extends ch.hilbri.assist.mappingdsl.AbstractMappingDSLRuntimeModule {

}
