/*
 * generated by Xtext 2.12.0
 */
package ch.hilbri.assist.scheduling.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SchedulingDslStandaloneSetup extends SchedulingDslStandaloneSetupGenerated {

	def static void doSetup() {
		new SchedulingDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
