/*
 * generated by Xtext 2.12.0
 */
package ch.hilbri.assist.scheduling.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SchedulingDslRuntimeModule extends AbstractSchedulingDslRuntimeModule {
}
